### ISSUE TITLE
Type of namespace "Client" could not be found.

### ISSUE THREAD

**Issue by takahser** [danielwertheim/mycouch#100]
I'm new to couchdb and mycouch. I'm trying to implement a very simple query, I just want to get the results of a view and save it into my DTO class.

My couchdb query works, when I query it manually via HTTP:

```
http://localhost:5984/mydb/_design/tshirts/_view/getAllTshirts
```

However, when I try running it from my app using mycouch, I can't get to run it. My current query:

```
using MyCouch.Requests;
using MyCouch.Responses;

// (...)

using (var client = new Client("http://localhost:5984/samples")) {
    var query = new QueryViewRequest("getAllTshirts");

    ViewQueryResponse<TShirt[]> result = await client.Views.QueryAsync<TShirt[]>(query);
    Console.WriteLine (result);
}
```

For some reason, it won't find the `Client` class. I found an example where `Client` is used on [github](https://github.com/danielwertheim/mycouch.aspnet.identity/blob/master/src/projects/MyCouch.AspNet.Identity.Net45/MyCouchUserStore.cs), as you can see, I'm using all the `MyCouch` related namespaces as in the example.

I also tried using `MyCouchStore` instead:

```
using (var store = new MyCouchStore("http://localhost:5984/", "samples")) {
    var query = new QueryViewRequest("getAllTshirts");
    ViewQueryResponse<TShirt[]> result = await store.Views.QueryAsync<TShirt[]>(query);
    Console.WriteLine (result);
}
```

However, the `store` doesn't contain any property named `Views`.
Any ideas how to query my view using MyCouch?

**Comment by danielwertheim** [comment]
The class is named MyCouchClient. The wiki contains info about views. MyCouchStore is an abstraction over the client, hence queries are written in another way. Currently on the move so...

**Comment by danielwertheim** [comment]
About MyCouchStore https://github.com/danielwertheim/mycouch/wiki/documentation#mycouchstore---an-opinionated-abstractionsimplification

About MyCouchClient and Views https://github.com/danielwertheim/mycouch/wiki/documentation#views-and-queries

**Comment by takahser** [comment]
Thanks for the information provided. I tried using MyCouchClient, as in the example I found in the  [documentation](https://github.com/danielwertheim/mycouch/wiki/documentation#user-content-get-connected):

    using (var client = new MyCouchClient("http://127.0.0.1:5984/test"))

However, it would throw me errors:

```
Error CS1502: The best overloaded method match for `MyCouch.MyCouchClient.MyCouchClient(MyCouch.DbConnectionInfo, MyCouch.MyCouchClientBootstrapper)' has some invalid arguments (CS1502)

Error CS1503: Argument `#1' cannot convert `string' expression to type `MyCouch.DbConnectionInfo' (CS1503)
```

**Comment by takahser** [comment]
Apparantely, the documentation was not up to date. The constructor requires now 2 arguments, the second being an optional bootstrapper. This worked for me:

	using (var client = new MyCouchClient("http://127.0.0.1:5984/test", null)) {

**Comment by takahser** [comment]
Sorry, I was mistaken, it wouldn't throw any exception anymore however, it still doesn't work properly:

		public async Task<IEnumerable<TShirt>> GetAll()
		{
			ViewQueryResponse<TShirt> result;
			List<TShirt> tshirts = null;

			// query couchdb
			using (var client = new MyCouchClient("http://localhost:5984/cshirts", null)) {
				// 1 - this is never reached
				var query = new QueryViewRequest("getAllTshirts");
				result = await client.Views.QueryAsync<TShirt>(query);
			}

			// convert result to List<TShirt>
			// 2 - this is never reached
			foreach (var row in result.Rows) {				
				var tshirt = new TShirt ();
				tshirt = row.Value;
				tshirts.Add (tshirt);
			}

			// 3 - this is never reached
			return tshirts;
		}

When this function is being called, it would never return. Please find the lines marked with 1/2/3, why won't these lines never be reached?
Thank you.

**Comment by danielwertheim** [comment]
Constructor first arg is server, second arg (where you pass null) is
dbName, and dbName is not allowed to be null hence argument exception is
thrown.

**Comment by danielwertheim** [comment]
As I have not heard anything with regards to the second argument (where you passed null), I'm closing this.
