### ISSUE TITLE
Query between 2 dates? 

### ISSUE THREAD

**Issue by koonj** [danielwertheim/mycouch#101]
Hi, 

I'm new to Couchdb and trying to practice CURD with MyCouch. 
Using VS 2015, I'm able to create database "foo" with following code. 
`
 private async void startButton_Click(object sender, RoutedEventArgs e)
        {           
            var task = Test();
            var result = await task;
            textBlock.Text = "Total Reading:" + result;
        }

 private async Task<int> Test()
        {
            int i = 0;
            using (var client = new MyCouchClient("http://localhost:5984/", "foo"))
            {
                var db = await client.Database.PutAsync();
                for (i = 0; i < 100; i++)
                {
                    var put = await client.Entities.PutAsync(
                    new Person { Id = "persons/" + i, Name = "F" + i, StartDate = DateTime.Now, EndDate = Some Date });
                }               
            }
            return i;
        }
 public class Person
        {
            public string Id { get; set; }
            public string Name { get; set; }
	    public DateTime StartDate {get; set;}
	   public DateTime EndDate {get; set;}
        }
`

I want to query the Id and Name in between StartDate and EndDate. 
Sample code will be helpful. 

Thanks

**Comment by danielwertheim** [comment]
You would need to define and "index" also known as a View in Couch that you then can query.

https://github.com/danielwertheim/mycouch/wiki/documentation#views-and-queries

Here is something I did a while ago with dates: http://danielwertheim.se/couchdb-partioned-dates-and-group-levels-to-control-aggregation-granularity/

In "the book": http://guide.couchdb.org/draft/views.html
