### ISSUE TITLE
Disabling the Entity Materializer

### ISSUE THREAD

**Issue by reddyBell** [danielwertheim/mycouch#102]
I've been fightinh with that one for two days without getting onto the root of the issue.
I often use inheritance and need to deserialize to a base class (which is sometimes abstract), therefore using the JSON.NET setting : TypeNameHandling = TypeNameHandling.All is a must for me.

However, when I adjust the bootstrapper to set this setting, I am getting the following exception :

Newtonsoft.Json.JsonSerializationException: Type specified in JSON 'MyNamespace.MyType, MyAsembly, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' is not compatible with 'MyCouch.Responses.Materializers.EntityResponseMaterializer+Temp, MyCouch.Net45, Version=4.0.0.3, Culture=neutral, PublicKeyToken=null'. Path '$type', line 1, position 245.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, String qualifiedTypeName)

I gather that you initially deserialize to some intermediary type. What is the recommended way to achieve what I am after ? I thought I'd save time by using MyCouch, instead of writing my own stuff - which I usually do - by I ended up wasting 2 days on this small issue while being on a very tight deadline :(

**Comment by danielwertheim** [comment]
TypeHandling is nothing that is supported. Perhaps redesign persisted doc
schema with an outer doc with different embedded docs for different
variations and handle it somehow in your app.

Or you can use the raw API and deserialize in your app.

Haven't had the need and I don't have the codebase fresh in my head, but...

Maybe you can copy that materializer and change it and hook it in.

Or hook in a customized version of serializer that tweaks the writer and
reader to look at other prop for determining type.

**Comment by reddyBell** [comment]
Thanks a lot for your prompt reply, I'll look into doing that. Tried with a custom serializer but got obscure null reference exceptions in the entity materializer while reading the response.

I'll quickly look into the raw API, otherwise forking seems to be the way to go since it is unsupported.

Thanks
