### ISSUE TITLE
Delete by specifying entity Id instead of entire entity.

### ISSUE THREAD

**Issue by JoshMcCullough** [danielwertheim/mycouch#103]
E.g. `client.Entities.DeleteAsync(myEntity.MySuperSpecificIdProperty)`

It's be great if there was an overload so I didn't have to pass the entire entity. This is useful when entities have "unpredictable" Ids, e.g. `PersonId`, `MyEntityId`, etc. (I realize these _are_ predictable, but less-so than simply using `Id` everywhere.

I realize I can inject a custom `IEntityReflector` instance, and I'll do this for now -- but it would be nice to be able to just pass an Id in this case.

Edit: After looking at the implementation for `EntityIdMember`, I see it will likely work out-of-the-box in most cases, but a `Delete(id)` API would still be nice.

**Comment by danielwertheim** [comment]
Will any of these do?

Please note, that in the case where `rev` is not provided, an additional lookup is done for that.

* https://github.com/danielwertheim/mycouch/blob/master/source/projects/MyCouch/IDocuments.cs#L183
* https://github.com/danielwertheim/mycouch/blob/master/source/projects/MyCouch/IMyCouchStore.cs#L139
* https://github.com/danielwertheim/mycouch/blob/master/source/projects/MyCouch/IMyCouchStore.cs#L149

**Comment by JoshMcCullough** [comment]
Yes, probably. I was working directly with `client.Entities` but perhaps can use an `IMyCouhcStore` instead. Thanks for the `rev` tip.

**Comment by danielwertheim** [comment]
And yes to comment on the Entity conventions, it should work in most cases. Look here: https://github.com/danielwertheim/mycouch/wiki/documentation#_id

**Comment by JoshMcCullough** [comment]
The problem with the conventions and the built-in `EntityIdMember` class is that it requires the property to be a string. So I wrote an `IEntityMember` implementation which accepts an `IdSelector` expression and a `ValueConverter` and handles getting/setting the referenced property and converting the value to string, as needed. Let me know if you think that's a useful addition to your library.
