### ISSUE TITLE
Problem with dates in IncludedDoc

### ISSUE THREAD

**Issue by arekdygas** [danielwertheim/mycouch#105]
Hello,

In our documents, dates are stored with milliseconds part (3 digits). Recently, when processing results from `MyCouchClient.Views.QueryAsync`, I noticed that one of our dates lost milliseconds part. After a bit of investigation, I see that the problem lies inside `MultiTypeDeserializationJsonConverter.ReadJsonAsString` method. When `WriteToken`is called, it internally reads date, and then writes it to string skipping trailing zeros (because `DateFormatString` in writer is null).

I believe a better solution would be reading dates as strings, not as actual dates. Firstly, it would create an exact copy, and secondly, it should be faster, because it skips string->date->string conversions.

Required change in `ReadJsonAsString`:

```
    var oldDateParseHandling = reader.DateParseHandling;
    reader.DateParseHandling = DateParseHandling.None;
    w.WriteToken(reader, true);
    reader.DateParseHandling = oldDateParseHandling; // restore previous handling
```

Similar change should be included in `ReadJsonAsStringArray`.

Best regards,
Arek

**Comment by danielwertheim** [comment]
If it should be treated as string, then use string in your entity instead
of DateTime. Or what am I missing?

**Comment by danielwertheim** [comment]
You could also use the MyCouchClientBootstrapper and configure the
SerializationConfig with an IsoDateTimeConverter that has the proper
DateTimeFormat
On 7 Jun 2016 13:02, "Daniel Wertheim" <daniel@wertheim.se> wrote:

If it should be treated as string, then use string in your entity instead
of DateTime. Or what am I missing?

**Comment by arekdygas** [comment]
If I were using `IncludedDoc `content for deserialization, then there would be no problem, but unfortunately I sometimes require processing raw string, using e.g. regular expressions, and that's when the problem occurred.

For example, this document:

```
{
   "_id": "1",
   "_rev": "1-46163943bbabb538589151dd646aa04f",
   "dt": "2000-10-10T01:02:03.00Z"
}
```

becomes

```
{
   "_id": "1",
   "_rev": "1-46163943bbabb538589151dd646aa04f",
   "dt": "2000-10-10T01:02:03Z"
}
```

And then regular expression test fails. Of course I can change regex pattern or, as you proposed, use `MyCouchClientBootstrapper`, but I believe the solution from OP is better. It guarantees that date strings will be exactly the same as in document returned by CouchDb. Plus it provides a slight performance gain of MyCouch queries, when `IncludedDoc `or `Value `contain dates.

**Comment by danielwertheim** [comment]
I do not want to introduce code like that. What I rather would to is to ensure that the settings for configuring the JSON serializer, also is applied there.

**Comment by arekdygas** [comment]
Applying serializer settings to a writer created in ReadJsonAsString would help, but I still don't understand, why you prefer this solution (read string, convert it to date according to reader settings, convert it to string according to writer settings, write string), over copying raw string data from reader to writer. Please remember, that it affects only one specific case, when either TValue or TIncludedDoc (of ViewQueryResponse<TValue, TIncludedDoc>) is string.

If there were a JsonWriter method CopyObjectAsString(JsonReader reader), I think using it would be ideal. Unfortunately there's no such method, and WriteToken doesn't output an exact copy with default settings.

Could you please share your concerns regarding my solution? Could it affects negatively any specific cases?
