### ISSUE TITLE
Include conflicts in QueryViewRequest

### ISSUE THREAD

**Issue by erichdev** [danielwertheim/mycouch#106]
Is it possible to include conflicts in an _all_docs `QueryViewRequest`? If I'm understanding correctly, only `GetDocumentRequest`has a Conflicts property, and this request is used to retrieve a single document. Thank you!

**Comment by danielwertheim** [comment]
There's no support for it no. You could add a `CustomQueryParameter` and then query it raw and parse the JSON.
