### ISSUE TITLE
Can I sort?

### ISSUE THREAD

**Issue by juangallo** [danielwertheim/mycouch#107]
Hi all,

I am using MyCouch to access a Cloudant database (The dll I have imported is 'MyCouch.Net45'). I have created a search query on Cloudant and I am using the following code to get the data I want:
```
var ll = new QueryViewRequest("mosquitos", "imei").Configure(query => query
         .Skip(skip)
         .Limit(_RecordsPerPage)
         .Reduce(false)
         .IncludeDocs(true));
     Task.Run(async () =>
     {
          ViewQueryResponse<string[]> result = await client.Views.QueryAsync<string[]>(ll);
```
I want to get the records sorted by time, and I am not finding the way to do this. Can you help me on this?
Thank you very much.

**Comment by danielwertheim** [comment]
Noticed that you closed but it's documented here:
https://github.com/danielwertheim/mycouch/wiki/documentation#views-and-queries

When querying a view in Couch, it's only sorted on the keys. By default
ascending, but you can state descending as well.
