### ISSUE TITLE
Question, is it possible?

### ISSUE THREAD

**Issue by juangallo** [danielwertheim/mycouch#108]
Let's say I have a cloudant database, with lots of records of multiple trucks that contain a truckid, and a timestamp to determine at what time this record was created. Is it possible with your extension to get the last record for a group of these trucks? If not, is it possible to get the last record for all trucks?
Thanks in advance for your help!
Regards,
Juan Martin

**Comment by danielwertheim** [comment]
I can honestly say that it was a long time since I was sitting with this so... Lets start like this.

How would the call be made in something like cUrl? As in, how would it look if we don't expect any client in between?

**Comment by juangallo** [comment]
Hey Daniel, 
What I was trying to explain is done here: 
[http://stackoverflow.com/questions/5637412/getting-a-list-of-documents-with-a-maximum-field-value-from-couchdb-view]
We solved it adding this view.
Thanks!
