### ISSUE TITLE
Attachments.PutAsync : Exception "Unexpected character encountered..."

### ISSUE THREAD

**Issue by Maxima078** [danielwertheim/mycouch#109]
Hi,
I'm trying to use mycouch but facing an issue when errors occured after a successful PUT.
The Newtonsoft (9.0.1) exception I got from within Attachments.PutAsync is "Unexpected character encountered while parsing value: <. Path '', line 0, position 0".

My use case is very simple, I just throw manually an exception after a successful Attachments.PutAsync(...), then the next time I'll call Attachments.PutAsync(...) on the same document with a different filename or with the same filename, that excetion is thrown within PutAsync method. 

I noticed if I change the scheme for instance from http to https or the port, the first next call to PutAsync is successful but after an my excetion is manually thrown the second call failed and I get that exception.

I'm thinking about a cache refresh probleme somewhere in HttpWebRequest but I don't really now what I'm looking for, have you already faced this issue ?

Thanks.

Max.

**Comment by danielwertheim** [comment]
Have you tried the exact same URL in cUrl or Postman? The error you get is
usually an indicator that you are hitting an endpoint that renders HTML.

**Comment by Maxima078** [comment]
I'll try with postman and post the result but with exactly the same url and same file, the attachment is supposed to be overwritten isn't it?

**Comment by Maxima078** [comment]
My bad it looks like a proxy configuration issue. While analyzing traffic I can see from my httpd proxy "502 bad gateway - The proxy server received an invalid response from an upstream server.".

**Comment by danielwertheim** [comment]
Closing due to not an issue. Feel free to re-open if I interpreted it wrong.
