### ISSUE TITLE
please check

### ISSUE THREAD

**Issue by foxjazz** [danielwertheim/mycouch#113]
when I call this function in code, and then look at the db in faulkton, the data is set as a  key and the value is null. So I think an issue with this.
 await client.Documents.PostAsync("{\"name\":\"Daniel\"}");

**Comment by danielwertheim** [comment]
Escape the string as e.g. the read me shows. That overload makes use of JSON.

Just tried this and it worked.

```csharp
class Program
{
    static void Main(string[] args)
    {
        TestThis().Wait();
    }

    static async Task TestThis()
    {
        using (var client = new MyCouchClient("http://192.168.2.20:5984/", "foo"))
        {
            var r = await client.Documents.PostAsync("{\"name\":\"Daniel\"}").ConfigureAwait(false);

            var x = client.Documents.GetAsync(r.Id);

            Console.WriteLine(x.Result.Content);
        }
    }
}
```

**Comment by danielwertheim** [comment]
Any feedback on this?

**Comment by danielwertheim** [comment]
Closing due to no response and due to tested that it works (see above) and also having tests for it.
