### ISSUE TITLE
NullReferenceException when set CustomQueryParameters

### ISSUE THREAD

**Issue by ksokolowski7** [danielwertheim/mycouch#114]
Hi,

When I use QueryAsync with custom query parameters an exception is thrown "Exception thrown: 'System.NullReferenceException' in MyCouch.Net45.dll".

I use this method from MyCouchStore. When I set parameter by method CustomQueryParameters it is not set in Query object but parameter HasCustomQueryParameters is set on true. It causes the error in QueryAsync method.

I prepared fix for it. The pull request #115 was created for it.

**Comment by danielwertheim** [comment]
This has been merged to master and will be released soon as it will be part of next release which targets making MyCouch compatible with CouchDB 2.0 and dropping Cloudant as a specific client.

Branch: https://github.com/danielwertheim/mycouch/tree/feature-couchdb2
