### ISSUE TITLE
Support for .NETCoreApp,Version=v1.1.

### ISSUE THREAD

**Issue by jefersonsv** [danielwertheim/mycouch#116]
Can you add support to framework .NETCoreApp,Version=v1.1.?

I get the project from Nuget but this library is incompatible with the this version.

![2017-03-14 09-12-01](https://cloud.githubusercontent.com/assets/1466570/23900043/67916236-0896-11e7-8382-2878cb14b7b1.png)

**Comment by nmtoan07** [comment]
@jefersonsv 
Other client libraries have been created by third parties or are no longer officially supported. :(
I hope IBM Bluemix team will create a sdk for .net soon

**Comment by danielwertheim** [comment]
@nmtoan07 I have had contact with Cloudant very early and it is now a IBM owned company and as I recall it, there was no interest in taking ownership.

@jefersonsv I'll try and get something out. Since I don't run tests etc against Cloudant anymore I will remove that part though. What I need to spend time on is to look into what parts can be moved into the core driver part, from the Cloudant one, as with the release of v2.0.0 of CouchDB some stuff in there should be supported, like searches.

**Comment by jefersonsv** [comment]
I have done the porting source code to .NETCoreApp,Version=v1.1.
I published this version, see: https://github.com/jefersonsv/MyCouch.Core

@danielwertheim do you authorize that  I make it?

**Comment by danielwertheim** [comment]
I started today to upgrade and have pulled in the PRs with bugfixes. Also updating to support CouchDB 2.0. Aiming at getting that out during the weekend.

Feels weird if you are going out with another version under the MyCouch name. I can push my work to a branch and then you could focus on getting that one to support .Net Standard. How does that sound?

**Comment by jefersonsv** [comment]
Very good ideia @danielwertheim , please create a new branch in your repository. I will delete my github repository and I going to work with your branch. 

Thanks,

**Comment by danielwertheim** [comment]
https://github.com/danielwertheim/mycouch/tree/feature-couchdb2

I've got all tests running green now for CouchDB2.0 (single node). Will focus on lifting over stuff from Cloudant specific driver to core one and then remove the Cloudant specific stuff.

**Comment by jefersonsv** [comment]
I think is most important to work in version CouchDB2.0 therefore the branch feature-couchdb2.

I will work on this branch

**Comment by danielwertheim** [comment]
The work has been done in feature branch and is included in #117 so closing this one.
