### ISSUE TITLE
Update to work against CouchDB 2.0

### ISSUE THREAD

**Issue by danielwertheim** [danielwertheim/mycouch#117]
Make it work against single-node CouchDB 2.0 and remove Cloudant specific driver

- [x] Move Index and Query stuff to core client from Cloudant client
- [x] Move Searches stuff to core client from Cloudant client
- [x] Remove Cloudant projects
- [x] What to do with searches stuff?
- [x] Convert to .Net standard 1.x

**Comment by jefersonsv** [comment]
I will remote the Cloudant specific driver. Do you will work in Cloudant specific driver separately?

**Comment by danielwertheim** [comment]
@jefersonsv  I have removed the Cloudant specific projects and merged the code into core

**Comment by willholley** [comment]
@danielwertheim Cloudant Search is open source but still requires a user to explicitly integrate it with CouchDB. I'm not sure it will ever be part of CouchDB core but perhaps would be a plugin of some kind.

**Comment by danielwertheim** [comment]
@willholley will remove it for now and see if anyone wants it. Dropping support for explicit Cloudant client.

**Comment by danielwertheim** [comment]
@jefersonsv code is converted and cleaned up so now it's only one MyCouch lib and it targets .Net Standard 1.1, so just build script left
