### ISSUE TITLE
Changes.ObserveContinuous stops pulling changes after 9 tries

### ISSUE THREAD

**Issue by eddieadl** [danielwertheim/mycouch#121]
Hello Daniel, 

I'm using the following code to consume the changes feed for updating an external database (using the function DataManager.SendCustomerToPriority). 
I'm getting the heartbeats 9 times and after that it stops trying to pull data from the changes feed. 
During these heartbeats, if there was any change in a document, I get it correctly, but after that nothing happens (no error at all and  other thread of the program continues to work properly). 

Do you have any idea why I get this behavior ?

Thanks, 
Eddie

var changesRequest = new GetChangesRequest { Feed = ChangesFeed.Continuous, IncludeDocs = true, Heartbeat = 1000, Since = lastSequence };
var cancellation = new CancellationTokenSource();

var changes = SUT.ObserveContinuous(changesRequest, cancellation.Token);
changes.Subscribe(new MyObserver
{
InterceptOnNext = v =>
{                   
DataManager.SendCustomerToPriority(v);                    
}
});
SpinWait.SpinUntil(() => cancellation.IsCancellationRequested);

**Comment by altgov3en** [comment]
Any update on the issue?

**Comment by gbiellem** [comment]
I had a similiar issue.  Turned out I had not set the timeout on the client connection to infinite. See https://github.com/danielwertheim/mycouch/wiki/documentation#continuous-feed
Once I adjusted this the continuous feed worked flawlessly for me.

Hope this helps you out

**Comment by danielwertheim** [comment]
Totally forgotten that I even documented it.
