### ISSUE TITLE
Correct way to query multiple types of entities

### ISSUE THREAD

**Issue by sventepe** [danielwertheim/mycouch#122]
Hi,

I have multiple types of entities which I query in a single view, e.g. **Car** and **Person**. If I use this, I get the docs as string:
`var request = new MyCouch.Requests.QueryViewRequest("Views_Doc", "MyView");`
`request.Configure(q => q.IncludeDocs(true));`
`var queryResult = DataService.Instance.Client.Views.QueryAsync(request);`

If I use this, I get all docs as **Car** although they are of doctype **Person**:
`var request = new MyCouch.Requests.QueryViewRequest("Views_Doc", "MyView");`
`request.Configure(q => q.IncludeDocs(true));`
`var queryResult = DataService.Instance.Client.Views.QueryAsync<string,Car>(request);`

How can I query the entities mapped to their classes? A workaround would be  creating a view for each doctype, but I don't only have 2 types, so that would mean a lot of Code for me. I would prefer a more generic approach.

Thanks!

Sven

**Comment by sventepe** [comment]
Somehow I closed this by accident.

**Comment by danielwertheim** [comment]
Really delayed answer...but... there is sadly nothing in there for that. Maybe there could be a generic version where one could use a OneOf construct or something. Haven't planned for anything like it.
