### ISSUE TITLE
ChangesResponse.cs is missing "Pending"

### ISSUE THREAD

**Issue by BewareOfWombat** [danielwertheim/mycouch#123]
The changesfeed response is missing the Pending object ( http://docs.couchdb.org/en/2.0.0/api/database/changes.html )

Response JSON Object:
    last_seq (json) – Last change update sequence
    pending (number) – Count of remaining items in the feed
    results (array) – Changes made to a database

**Comment by rafsojka** [comment]
Is there any view on adding the missing fields to the response?
