### ISSUE TITLE
Entity must have _id and _rev property in order to persist.

### ISSUE THREAD

**Issue by JoshMcCullough** [danielwertheim/mycouch#124]
It seems that MyCouch requires entities to have an `_id` and `_rev` property, otherwise I cannot persist an entity via the `Entities` API. I get the following error when I try to add or update an entity without these properties via: `couchClient.Entities.PutAsync(id, entity)`

I can get around this by using the `Document` API and serializing/deserializing my entity manually (via Json.NET, of course).

Is this the correct behavior? If so, why is it so? Thank you!

> System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type.
>    at System.Delegate.CreateDelegateNoSecurityCheck(Type type, Object target, RuntimeMethodHandle method)
>    at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType)
>    at MyCouch.EntitySchemes.Reflections.IlDynamicPropertyFactory.CreateIlGetter(PropertyInfo property)
>    at MyCouch.EntitySchemes.Reflections.IlDynamicPropertyFactory.CreateStringGetter(PropertyInfo property)
>    at MyCouch.EntitySchemes.Reflections.IlDynamicPropertyFactory.PropertyFor(PropertyInfo property)
>    at MyCouch.EntitySchemes.EntityMember.<>c__DisplayClass13_0.<GetSetterFor>b__0(Type t)
>    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
>    at MyCouch.EntitySchemes.EntityMember.GetSetterFor(Type type)
>    at MyCouch.EntitySchemes.EntityMember.SetValueTo[T](T entity, String value)
>    at MyCouch.Contexts.Entities.<ProcessEntityResponseAsync>d__38`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MyCouch.Contexts.Entities.<PutAsync>d__34`1.MoveNext()

**Comment by danielwertheim** [comment]
https://github.com/danielwertheim/mycouch/wiki/documentation#documents-vs-entities

CouchDB requires id and rev, that's why the entity has those requirements.

**Comment by JoshMcCullough** [comment]
Thanks for the reply. I understand that these are required by CouchDB. However, I assumed the MyCouch client would handle this gracefully, especially when I provide an `id` and `rev` in the API call (e.g. `client.Entities.PutAsync(id, rev, entity)`). In this case, MyCouch already knows the `id` and `rev`, but it still tries to get it off of (or set it onto) the entity.

**Comment by danielwertheim** [comment]
Use the `Documents` context and you have no constraints. You could e.g. write a extension method against `IDocuments` or wrap it in something else, where you use what ever serializer you want.

Although, it looks in the code as it should work with an explicit id apart from in step (4) below:

(1) https://github.com/danielwertheim/mycouch/blob/master/source/projects/MyCouch/Contexts/Entities.cs#L79

(2) https://github.com/danielwertheim/mycouch/blob/master/source/projects/MyCouch/Requests/PutEntityRequest.cs#L69

(3) https://github.com/danielwertheim/mycouch/blob/master/source/projects/MyCouch/HttpRequestFactories/PutEntityHttpRequestFactory.cs#L39

(4)
https://github.com/danielwertheim/mycouch/blob/master/source/projects/MyCouch/Contexts/Entities.cs#L131

Honestly, I don't remember if this was the intentions or not. And that step 4 is "wrong". Haven't looked into tests to see if it works as intended.
