### ISSUE TITLE
Entity vs. Document API performance.

### ISSUE THREAD

**Issue by JoshMcCullough** [danielwertheim/mycouch#125]
While fixing issues related to #124, we switched from using the Entity API to the Document API. So now we get entities by first getting the _document_, and then using Json.NET's `JsonSerializer` and/or `JsonConvert` to serialize/serialize the document into the appropriate entity, manually.

_This simple change increased performance by an order of magnitude._

For instance, the same code running via the Entity API gives us a result in 4-5 seconds; when using the Document API, the same result is returned in 300-500 milliseconds. I'm not sure if it's our fault, or if there's something in the Entity API which is causing this performance issue. But I thought I'd post it here in case you had any insight.

**Using Entity API** (~4sec)

```
public virtual async Task<TEntity> Get(object id, string revision = null)
{
    var response = await this.Client.Entities.GetAsync<TEntity>(Convert.ToString(id), revision);

    if (response.IsSuccess) {
        return response.Content;
    }

    return null;
}
```

**Using Document API** (~500ms)

```
public virtual async Task<TEntity> Get(object id, string revision = null)
{
    var response = await this.Client.Documents.GetAsync(Convert.ToString(id), revision);
    TEntity result = null;

    if (response.IsSuccess)
    {
        result = JsonConvert.DeserializeObject<TEntity>(response.Content, _jsonSerializerSettings);
    }

    return result;
}
```

**Comment by danielwertheim** [comment]
Shouldn't be that big difference. The first time a new entity is seen it can take a bit more time to build meta about schema. But not that long. What version?

**Comment by JoshMcCullough** [comment]
`v4.0.0` -- I see MyCouch uses Json.NET under the hood, so I'm not sure why there's such a gap. Perhaps I'll write a quick app to test the two approaches and make sure I'm not delusional. :)

**Comment by danielwertheim** [comment]
Looked quickly and the single GET seem to have a leftover in there from an old requirement causing unnecessary deserialization. Will look into it more thoroughly later.

**Comment by JoshMcCullough** [comment]
Honestly, I can't reproduce the slowness in a test case I wrote last night. Entity/Document performance is basically equivalent. I'm looking into a few other changes I made around the same time to see if something else is the culprit, or if I'm just completely off my rocker. :)

**Comment by danielwertheim** [comment]
@JoshMcCullough can this be closed?

**Comment by JoshMcCullough** [comment]
Oops, meant to confirm it can be closed -- sorry!

**Comment by danielwertheim** [comment]
Np ;-)
