### ISSUE TITLE
change $doctype in doctype

### ISSUE THREAD

**Issue by russosalv** [danielwertheim/mycouch#129]
Can you change $doctype property in doctype.

the use of $ make impossible search it by Mango Queries

```
using MyCouch.Extensions;

namespace MyCouch.Serialization.Conventions
{
    public class SerializationConventions
    {
        public ISerializationConvention DocType { get; set; }
        public ISerializationConvention DocNamespace { get; set; }
        public ISerializationConvention DocVersion { get; set; }

        public virtual bool HasConventions
        {
            get { return DocType != null || DocNamespace != null || DocVersion != null; }
        }

        public SerializationConventions()
        {
            DocType = new StringSerializationConvention(
                //"$doctype",
                "doctype",
                m => !m.IsAnonymous ? m.DocType.ToCamelCase() : null);

            DocNamespace = new StringSerializationConvention(
                //"$docns",
                "docns",
                m => m.DocNamespace);

            DocVersion = new StringSerializationConvention(
                //"$docver",
                "docver",
                m => m.DocVersion);
        }
    }
}
```

**Comment by russosalv** [comment]
UP

**Comment by danielwertheim** [comment]
@russosalv the idea with `$` was to not mix it with "data" fields, but more "meta". I did not know that Mango didn't allow this. Changing this in MyCouch is definitely a breaking change but obviously something need to be done.

Regarding naming for the new field, I do think it should be prefixed, to indicate "non data field". Both `_` and `@` seem to work, leaning more towards `_`. Opinions?

**Comment by danielwertheim** [comment]
@russosalv the following works with CouchDB 2.1

```
{
  "selector": {
    "\\$doctype": {
      "$eq": "foo1"
    }
  }
}
```

**Comment by danielwertheim** [comment]
Also, the existing convention could be configured via the bootstrapper: https://github.com/danielwertheim/mycouch/blob/master/source/projects/MyCouch/MyCouchClientBootstrapper.cs#L21

Given that you could write the query as is (escaping the `$` sign) and that you also could reconfigure the conventions, I'm leaning towards not doing any change.
