### ISSUE TITLE
File not found mycouch.dll

### ISSUE THREAD

**Issue by DanTDMMcpe** [danielwertheim/mycouch#131]
I am using Visual Studio 2017 15.3.4

I am making a C# UWP app.

Now my problem is that when I call "using (var client = new MyCouchClient("http://127.0.0.1:5984", "testdb"))
{
    //Consume here
}"

It throws a "System.IO.FileNotFoundException in mycouch.dll"

Then it crashes.

What am I doing wrong?

I need your help please.

Ps.

I am using MyCouch 5.0.1

**Comment by danielwertheim** [comment]
I just created an UWP app (targeting Windows 10 Creators Update) and after adding network capabilities in the manifest, it worked fine running it locally against my CouchDB server.

**Comment by DanTDMMcpe** [comment]
Dear @danielwertheim 

Thank you for your reply.

I have enabled the  "Internet (Client & Server)" capability in the manifest.
Is that correct?

The code is this: 

 `private async void SubscribeButton_Click(object sender, RoutedEventArgs e)
        {
            using (var client = new MyCouchClient("http://danielwertheim1:testtest1@localhost:5984", "hello"))
            {
                string artistJson = "{\"_id\": \"4\", \"$doctype\": \"artist\",\"name\": \"Fake artist 1\",\"albums\":[{\"name\": \"Greatest fakes #1\", \"tracks\": 3}]}";
                await client.Documents.PostAsync(artistJson);
            }
        }`


Is that correct?

And here are the exceptions using Managed & Native debugging:

Exception thrown at 0x763EB832 in HololensDB.exe: Microsoft C++ exception: EEFileLoadException at memory location 0x071FB414.
Exception thrown at 0x763EB832 in HololensDB.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
Exception thrown at 0x763EB832 in HololensDB.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
Exception thrown at 0x763EB832 in HololensDB.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
Exception thrown: 'System.IO.FileNotFoundException' in MyCouch.dll
Exception thrown: 'System.IO.FileNotFoundException' in System.Private.CoreLib.ni.dll
Exception thrown at 0x763EB832 (KernelBase.dll) in HololensDB.exe: 0x40080201: WinRT originate error (parameters: 0x80070002, 0x00000200, 0x071FED50).
Exception thrown at 0x763EB832 (KernelBase.dll) in HololensDB.exe: 0x40080201: WinRT originate error (parameters: 0x80070002, 0x00000090, 0x071FEFD8).

Thank you again for your help

-shukenmg

**Comment by danielwertheim** [comment]
Sorry, beats me.

I created a new C# UWP Blank app and added a button and added similar code to yours. I got an unauthorized exception but that was due to capabilities that I fixed, then it worked.

I target:
![image](https://user-images.githubusercontent.com/196044/30628644-d45f9ee2-9dd7-11e7-82b9-faedb0211fef.png)

Run it on a machine with 

![image](https://user-images.githubusercontent.com/196044/30628660-e737aa00-9dd7-11e7-9c9c-a6b4dde2980d.png)

**Comment by DanTDMMcpe** [comment]
@danielwertheim 

Could you send me your project?
Then i could test.

**Comment by DanTDMMcpe** [comment]
Hey i just fixed the problem by making a new project and installing MyCouch.

Thanks for your help @danielwertheim 

-Shukenmg

**Comment by DanTDMMcpe** [comment]
I have some more problems.

When i use this 

 var query = new QueryViewRequest("artists", "albums").Configure(query => query
                 .Limit(5)
                 .Reduce(false));
                ViewQueryResponse<string> result = await client.Views.QueryAsync<string>(query);
                this.TextLOL.Text = result.ToString();

There is this error


Error	CS0136	A local or parameter named 'query' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter

![errordc](https://user-images.githubusercontent.com/18000205/30645186-7a750ff0-9e47-11e7-9ea2-d3b227597c21.PNG)

What is the problem here now?

**Comment by danielwertheim** [comment]
As it says. You define the variable name to query as well as the lambda variable name to query. Change one.

**Comment by DanTDMMcpe** [comment]
Ok ill try

@danielwertheim 

Here is another problem (Sorry for bothering you but i really can't get it to work )

![use](https://user-images.githubusercontent.com/18000205/30645636-e2b0af7e-9e48-11e7-8230-1ba413d3e7d9.PNG)
This code works (it creates a document in CouchDB)
But the response is this
![resp](https://user-images.githubusercontent.com/18000205/30645679-08464190-9e49-11e7-8e24-fe766ee121d2.PNG)
What is the problem?

Thank you for your help.

**Comment by danielwertheim** [comment]
Async method is not awaited.

**Comment by DanTDMMcpe** [comment]
@danielwertheim 

Ok thank you i'll test it now.

**Comment by DanTDMMcpe** [comment]
![res2](https://user-images.githubusercontent.com/18000205/30646143-92eac28e-9e4a-11e7-9575-3231a222ce87.PNG)

@danielwertheim 

Thank you

Here is what i am getting.

Is that correct?

**Comment by DanTDMMcpe** [comment]
@danielwertheim By the way this is the result of the query
My code
![back](https://user-images.githubusercontent.com/18000205/30646247-f4140c5a-9e4a-11e7-948f-53642101f120.PNG)

The response.
![res3](https://user-images.githubusercontent.com/18000205/30646249-f4259740-9e4a-11e7-8376-b6c286239dab.PNG)

Sorry for my stupidity.
:(

**Comment by DanTDMMcpe** [comment]
@danielwertheim 

Hey so for the query i found that i needed to use 
this.TextLOL.Text = result.ToStringDebugVersion();
instead of 
this.TextLOL.Text = result.ToString();

So thats one problem solved

Thank you again for your help and patience.

**Comment by danielwertheim** [comment]
Have you looked in the Wiki? You can use entities etc.

**Comment by DanTDMMcpe** [comment]
How would i get the name of a row and put it on a text box?

@danielwertheim

**Comment by danielwertheim** [comment]
For queries (retrieving 0-n documents): https://github.com/danielwertheim/mycouch/wiki/documentation#views-and-queries

Note, MyCouch allows two tracks, documents vs entities: https://github.com/danielwertheim/mycouch/wiki/documentation#documents-vs-entities

I'm closing this for now.
