### ISSUE TITLE
MyCouch version 5 appears to have compatibility issues with EnsureThat 6 or newer.

### ISSUE THREAD

**Issue by anevilyak** [danielwertheim/mycouch#132]
After updating EnsureThat to 6.0 in one of our projects that also uses MyCouch 5, the project now throws a FileNotFoundException the first time any use of MyCouch is involved. This appears to be partly due to the DLL having changed names from Ensure.That.dll to EnsureThat.dll.

**Comment by danielwertheim** [comment]
Oh-crap! Haven't even noticed the change in file names.

@anevilyak What would be preferred for you. Fix Ensure.That to have old name on DLL or release a new version of MyCouch that targets EnsureThat 6+?

**Comment by anevilyak** [comment]
For us, ideally a new version that targets 6 would be preferable, but if there's an alternative that's easier for you to implement (not sure if binding redirects could resolve this one due to the name difference), then whatever works :-).

**Comment by danielwertheim** [comment]
I'm thinking more projects might have that kind of issues (not just MyCouch) and perhaps the best would be to fix the output filename.

**Comment by anevilyak** [comment]
That's fine. Thanks for looking into it (and your hard work)!

**Comment by danielwertheim** [comment]
There is now a pre-rel of v6.0.1: https://www.nuget.org/packages/Ensure.That/6.0.1-pre28

Not sure if you could verify if that works before doing a stable fix-release?

**Comment by mattdefoor** [comment]
6.0.1-pre28 produces the following exception:

System.MissingMethodException occurred
  HResult=0x80131513
  Message=Method not found: 'EnsureThat.Param`1<System.String> EnsureThat.EnsureStringExtensions.IsNotNullOrWhiteSpace(EnsureThat.Param`1<System.String>)'.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at MyCouch.DbConnectionInfo..ctor(Uri serverAddress, String dbName)
   at <redacted>

**Comment by danielwertheim** [comment]
@mattdefoor @anevilyak new Release of MyCouch v5.0.2 has updated to Ensure.That 6.0.1

**Comment by anevilyak** [comment]
Confirmed fixed, thanks for the quick response!
