### ISSUE TITLE
New HttpClient used per instance of MyCouchClient.

### ISSUE THREAD

**Issue by JoshMcCullough** [danielwertheim/mycouch#135]
We noticed a ton of sockets destined for CouchDb being left in `TIME_WAIT` state after we had disposed of the MyCouch client. In high usage this would eventually cause our application to fail. Since each instance of MyCouch client is using its own instance of HttpClient, Windows will leave the socket in this state for 240 seconds (default) after the connection is closed/disposed.

I am thinking perhaps we are not using MyCouch in the correct way. Currently we create/dispose instance of the MyCouch client very often. Instead, perhaps we should try to keep them around as long as possible. 

So, two things ...

1. What is your recommendation regarding the lifetime of a MyCouch client?
2. Would you consider allowing for the injection of an HttpClient factory into `MyCouchClient` / `DbConnection` / `Connection`? Currently `Connection` is [hard-coded to create a new HttpClient](https://github.com/danielwertheim/mycouch/blob/master/source/projects/MyCouch/Net/Connection.cs#L66), but it seems we should be able to supply a factory instead.

More information here: https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

**Comment by danielwertheim** [comment]
It is my understanding that it should be shared.

Here's one post showing issues with HttpClient that are short lived https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

Do think this has been up in previous issues here on GitHub.

**Comment by JoshMcCullough** [comment]
We linked to the same post. :) Thanks -- we are going to end up using a single `MyCouchClient` instance per config / base URL.
