### ISSUE TITLE
DbConnectionInfo and host 

### ISSUE THREAD

**Issue by Maxima078** [danielwertheim/mycouch#136]
Hi,
I'm trying to create a DbConnectionInfo at: https://mydomain.com:443/cloud/mydatabasename
But it seems that the method "RemoveUserInfoFrom()" called within DbConnectionInfo ctor remove the /cloud part. I cannot manually set the Address property since there is no setter.

Is there another way to manually set the address of ConnectionInfo in order to create a MyCouchClient object?

Thank you.

**Comment by danielwertheim** [comment]
Unfortunately no. Can you get around it by passing some dummy basic credentials? E.g. `https://fooUsr:barPwd@mydomain.com:443/cloud/mydatabasename`

**Comment by Maxima078** [comment]
This does not work. I'm using 4.0.0 version and here is the code:

    var uri = new Uri($"{_Scheme}://foo:bar@{_Host}");
    DbConnectionInfo dbi = new DbConnectionInfo(uri, _DbName);
    dbi.BasicAuth = new MyCouch.Net.BasicAuthString(_Username, _Password);
    _myCouchClientAttachment = new MyCouchClient(dbi);

Is this trick supposed to work around it?

**Comment by Maxima078** [comment]
I could get around it with:
    
    var _Host="mydomain.com:443/cloud"
    var adress = $"{_Scheme}://{_Host}/dummytrailinghost";
    DbConnectionInfo dbi = new DbConnectionInfo(adress, _DbName);

By adding anything after mydomain.com:443/cloud the DbConnectionInfo ctor keep the /cloud part but remove /dummytrailinghost.

Will you fix it? This use case is a simple Reverse-proxy in front of several instance of CouchDB.

**Comment by danielwertheim** [comment]
The issue is the URI. When creating one with relative and the first part doesn't end with "/" it cuts of one part.

**Comment by danielwertheim** [comment]
You should be able to try: https://www.nuget.org/packages/MyCouch/5.0.3-pre18

**Comment by Maxima078** [comment]
Thank you it did the job !!
