### ISSUE TITLE
PostIndexRequest fails when explicitly setting Type

### ISSUE THREAD

**Issue by anevilyak** [danielwertheim/mycouch#137]
With version 5.0.2, if one creates a PostIndexRequest and actually sets Type = Json, the request fails with Couch returning "invalid index type: Json". Simply not setting that field works though, and as best I can tell, the problem is the type being serialized as "Json" rather than "json".

**Comment by danielwertheim** [comment]
OK, looks like ToString has been used instead of specific extension method: https://github.com/danielwertheim/mycouch/blob/master/source/projects/MyCouch/HttpRequestFactories/PostIndexHttpRequestFactory.cs#L45

Fix is on the way

**Comment by danielwertheim** [comment]
You should be able to try https://www.nuget.org/packages/MyCouch/5.0.3-pre18

**Comment by anevilyak** [comment]
Confirmed fixed, thanks!
