### ISSUE TITLE
Query list function with complex key

### ISSUE THREAD

**Issue by AlainBaslter** [danielwertheim/mycouch#139]
I have a view that generates  a complex key...
function (doc) {
	if ('MapServer' === doc.TypeName) {
		emit([doc.ServerId, doc._id], null);
	}
}
The id's are GUIDs as strings
{
	"total_rows":25,
	"offset":0,
	"rows":
	[
		{
			"id":"1a187e32-2a61-4ba3-993a-e2c39030933d",
			"key":
			[
				"6090b408-92bb-46b6-9ecb-d12266a39ee2",
				"1a187e32-2a61-4ba3-993a-e2c39030933d"
			],
			"value":null
		},
		{
			"id":"213b0b8d-c842-45ea-bca3-e652d0794861",
			"key":
			[
				"6090b408-92bb-46b6-9ecb-d12266a39ee2",
				"213b0b8d-c842-45ea-bca3-e652d0794861"
			],
			"value":null
		},
...
Then I have a list function using that view
function (head, req) {
	var result = [];
	var row;
	while (row = getRow()) {
		var idname = {
			Id: row.doc._id,
			Name: row.doc.Name
		};
		result.push(idname);
	}
	send(toJSON(result));
}

I query this list in Postman and I get results...

http://localhost:5984/disco2018/_design/server_map_server/_view/Servers_MapServers?startkey=["6090b408-92bb-46b6-9ecb-d12266a39ee2"]&endkey=["6090b408-92bb-46b6-9ecb-d12266a39ee2",{}]&include_docs=true

But this does not work...

    public static async Task<JArray> ExecuteListFunctionAsync(  string databaseUrl, 
                                                                string databaseName,
                                                                string designDocName,
                                                                string viewName,
                                                                string listFunctionName, 
                                                                string[] startKey = null,
                                                                string[] endKey = null)
    {
      try
      {
        using (var client = new MyCouchClient(databaseUrl, databaseName))
        {
          var query = new QueryViewRequest(designDocName, viewName);
          query.Configure(c => 
            {
              c.WithList(listFunctionName);
              c.IncludeDocs(true);
              if (null != startKey)
              {
                c.StartKey<string>(startKey);
              }
              if (null != endKey)
              {
                c.EndKey<string>(endKey);
              }
            });
          var response = await client.Views.QueryRawAsync(query);
          var contentAsJson = JArray.Parse(response.Content);
          return contentAsJson;
        }
      }
      catch (Exception ex)
      {
        tracer(ex.ToString());
      }
      return null;
    }

I am passing in these...

        string[] startKey = { id };
        string[] endKey = { id, "{}" };

Supposedly just like I am doing in Postman.
I get no results no errors.

Am I doing something wrong or is there a bug?

**Comment by AlainBaslter** [comment]
Oh I found the answer digging into closed issue: Multi key views #98
Passing in
        object[] startKey = { id };
        object[] endKey = { id, new { } };
And using 
          query.Configure(c => 
            {
              c.WithList(listFunctionName);
              c.IncludeDocs(true);
              if (null != startKey)
              {
                c.StartKey<object>(startKey);
              }
              if (null != endKey)
              {
                c.EndKey<object>(endKey);
              }
            });
Works like a charm.
Hopefully this helps someone one day.

**Comment by danielwertheim** [comment]
I do think it should work with just an anonymous object as well and not an array:

https://github.com/danielwertheim/mycouch/blob/master/source/projects/MyCouch/QueryViewParametersConfigurator.cs#L117
