### ISSUE TITLE
Store new Document with C# Object as Object in Document

### ISSUE THREAD

**Issue by alexleo2000** [danielwertheim/mycouch#140]
## Store Document
I am new to Package, and I wanted to store a new Document in CouchDB. This was no Problem, but when I wanted to store a new Document with some Information in it like that:
`var client = new MyCouchStore("http://admin:admin@127.0.0.1:5984/", "workers");`
`var mySomething = await client.StoreAsync(new Something("test", "test", 21));`

the Object in the Document where not the "name":"test" or "age": "test", instead there only was "$doctype": "something". So I wanted to ask, if it is possible to store an Object in a new Document like that, or if there is any other option to do that.

**Comment by danielwertheim** [comment]
First understand the difference between documents and entities within MyCouch: https://github.com/danielwertheim/mycouch/wiki/documentation#documents-vs-entities

Regarding usage of `MyCouchStore` and not the `MyCouchClient` you should know that the first one is an opinionated wrapper on top of the `MyCouchClient`.

Have a look at the integration tests, more precisely the "flow tests" for documents and entities with MyCouchStore:

- https://github.com/danielwertheim/mycouch/blob/master/source/tests/MyCouch.IntegrationTests/CoreTests/MyCouchStoreCrudTests.cs#L16

- https://github.com/danielwertheim/mycouch/blob/master/source/tests/MyCouch.IntegrationTests/CoreTests/MyCouchStoreCrudTests.cs#L33

**Comment by alexleo2000** [comment]
Thanks for your quick answer, now I know how it works and I'm able to complete my Application!
