### ISSUE TITLE
 HttpClient scoping?

### ISSUE THREAD

**Issue by SimonCropp** [danielwertheim/mycouch#144]
out of curiosity does this article effect the scoping of your `HttpClient`s ?
https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

**Comment by danielwertheim** [comment]
Yes: https://github.com/danielwertheim/mycouch/issues/135

**Comment by danielwertheim** [comment]
Updated Wiki https://github.com/danielwertheim/mycouch/wiki/Documentation#understand-httpclient-scope

**Comment by SimonCropp** [comment]
Cool. And yep i should have read the doco. Thanks

**Comment by danielwertheim** [comment]
I added the info in the wiki after you opened the question/issue so that would be hard :-) I should have done that earlier.

**Comment by SimonCropp** [comment]
Ahh cool.
