### ISSUE TITLE
add GetAllDatabaseNames to IMyCouchServerClient ?

### ISSUE THREAD

**Issue by SimonCropp** [danielwertheim/mycouch#145]
would this be a sensible addition to IMyCouchServerClient ?

ie not as an extension method but as a real method

```
public static async Task<string[]> GetAllDatabaseNames(this IMyCouchServerClient server)
{
    var response = await server.Connection.SendAsync(new HttpRequest(HttpMethod.Get, "/_all_dbs")).ConfigureAwait(false);
    return server.Serializer.Deserialize<string[]>(await response.Content.ReadAsStringAsync().ConfigureAwait(false));
}
```

**Comment by danielwertheim** [comment]
The thing is that long time back there was someone (me) taking some decisions (oh-no) to make life a bit complicated by trying to have a component/class for everything that could be...

So the server client exposes an implementation of `IDatabases` e.g. https://github.com/danielwertheim/mycouch/blob/master/source/projects/MyCouch/Contexts/Databases.cs

And in there life isn't that simple as you describe above. Not sure if it can start being that simple and not follow the solution that is currently in there. Thoughts?

**Comment by SimonCropp** [comment]
sorry i dont think i have enough context to understand what you are aluding to

**Comment by danielwertheim** [comment]
The clients does not directly expose methods but "contextual" representations https://github.com/danielwertheim/mycouch/wiki/documentation#contextual-client

So the operation should in this case be added to the `IDatabases` interface and the implementation that the server client exposes. See the link. And in there life is further more "complicated" with request and response factories etc. So it's not "just" to use the connection and do a raw request if the existing "pattern" should be followed.
