### ISSUE TITLE
MyCouch 5.1 appears to have compatibility issues with Ensure.That 7.2.1

### ISSUE THREAD

**Issue by anevilyak** [danielwertheim/mycouch#146]
When attempting to use the above two together, one gets errors such as:

System.MissingMethodException: Method not found: 'System.String EnsureThat.StringArg.IsNotNullOrWhiteSpace(System.String, System.String)'.
   at MyCouch.DbConnectionInfo..ctor(Uri serverAddress, String dbName)

Whereas things work correctly when downgrading back to Ensure.That 7.1.0. Please let me know if you need any additional information.

**Comment by danielwertheim** [comment]
Released https://www.nuget.org/packages/MyCouch/5.1.1

Ensure.That introduces an new optional parameters instead of a overload hence the compatibility went...

**Comment by anevilyak** [comment]
Confirmed fixed, thanks!
