### ISSUE TITLE
Ability to filter document keys in GetChangesRequest

### ISSUE THREAD

**Issue by paweu** [danielwertheim/mycouch#148]
I need to listen to changes of speific objects only. Usually just a single key.

It would be nice if I could use `doc_ids` for that.

There are addtional ways to do that in CouchDB, like passing request parameters to filter function, or even better, using POST:
- doc_ids, or
- filter=_selector & BODY.selector = {query selector}

**Comment by danielwertheim** [comment]
If you have an idea of how it should look and work, feel free to provide a PR.

**Comment by Estman** [comment]
Hello,
I have the same issue.
I want to pass parameters to filter function.

`filter=_selector`

In body I can pass JSON.
`{
    "selector": {
        "_deleted": {"$exists": false}
    }
}`

When I will post the request I will not get _deleted documents.
Is there a way to do this?
Thank you.
