### ISSUE TITLE
CancellationToken

### ISSUE THREAD

**Issue by SimonCropp** [danielwertheim/mycouch#149]
Is there any info on why some asyn methods take a cancellation token and not others?

Also have u considered have a defaulted parameter instead of overloads?  ie 

    CancellationToken token = default(CancellationToken)

**Comment by danielwertheim** [comment]
No. If I remember it correctly from the beginning none had. Then there was a PR that added it... so, no. Would be good if there was an option for all the methods.

That would be an improvement, yes. But it would bump major version but that's OK.
