### ISSUE TITLE
ConnectionInfo: UseProxy is false

### ISSUE THREAD

**Issue by Maxima078** [danielwertheim/mycouch#151]
Hi,

Why UseProxy is set to false by default? Does it mean proxy set from system (let's say Windows 10) will not be used by default?
I'm facing proxy issues while getting attachment and found this UseProxy false...

How do you recommend to manage proxy configuration?

**Comment by danielwertheim** [comment]
`UseProxy` is used in conjunction with the `HttpClientHandler` https://github.com/danielwertheim/mycouch/blob/013ed13dc86a6db4d2712172404b95cd44d55c6b/source/projects/MyCouch/Net/Connection.cs#L63

All defaults has tried to be the default they operate on. So I hope `HttpClientHandler.UseProxy` was `false` by default.

So any recommendation for `HttpClient` and `HttpClientHandler` would also go for MyCouch.

**Comment by Maxima078** [comment]
Default value is true https://msdn.microsoft.com/fr-fr/library/system.net.http.httpclienthandler.useproxy(v=vs.110).aspx
I'll test if it fix my issue to change it to true.

**Comment by Maxima078** [comment]
Changing the default value from false to true fix my problem

**Comment by danielwertheim** [comment]
Released
