### ISSUE TITLE
SocketException : ConnectionReset with async/await

### ISSUE THREAD

**Issue by Maxima078** [danielwertheim/mycouch#154]
Hi,

I'm using 5.0.3 to download some attachments "asynchronously" but I'm facing random SocketException : ConnectionReset. I double checked my server (simple nginx in front of couchdb) logs and each time the problem occurs I can confirm the server returned HTTP 200 and the exact attachment size as "bytes sent". I also benchmarked my server with thousand concurrent requests and got no error.

Then I started to investigate the client side, I know about the way to use HttpClient (singleton, dispose) as mentioned [here](https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/) and [here](http://www.nimaara.com/2016/11/01/beware-of-the-net-httpclient/) thus when I implemented my client part with MyCouch I took care about making a MyCouch instance as a singleton. But that was probably(?) a mistake because, like I said I want to download several attachments asynchronously.
To do so, let's say I want to have 5 async donwloads, I simply have a list of groups with each group containing 5 ids to download. Then I start downloading them like this:

`var tasks = groups.Select(attObj => GetAttachmentAsync(attObj.Id)).ToList();`
`var results = await Task.WhenAll(tasks);`

With this implementation I get random ConnectionReset exceptions.

I've found 3 ways to fix it:
1- remove the singleton. This can seem weird, but even with 6000 downloads I got no error IF I create a new MyCouchClient each time I want to download an attachment
2- significantly increase the number of asynchronous requests: When increasing this number from 5 to 50 it fix my issue
3- create only 5 instances of MyCouchClient and use one per task: If I create a list of 5 instances and re-use them until app is closed it fix my issue

1st question: With MyCouchClient, is multiple asynchronous download possible? Let's say with one MyCouchClient instance I start downloading asynchronously 2 attachments, is it possible that when the first one finished the second get a wrong signal?

2nd question (depending on the 1st answer): If "yes", what am I doing wrong and why those three "patch" fix the issue? If "no", what is the correct way to do it with MyCouch? The third patch probably?

Thanks for any hints!

Max

**Comment by danielwertheim** [comment]
As I understand it, this is really a question about `HttpClient` and would be better asked as such on e.g. StackOverflow. One `MyCouchClient` uses one `HttpClient`.

Could it be that you are hitting the max num of connection against the same "host"? https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/network/connectionmanagement-element-network-settings

**Comment by Maxima078** [comment]
Thank you for your answer I'll try from StackOverflow.
Changing maxconnection is a good point I'll also give it a try.
