### ISSUE TITLE
How to change timeout

### ISSUE THREAD

**Issue by Maxima078** [danielwertheim/mycouch#155]
Hi,

Currently the only way to set timeout is to set it before MyCouchClient creation through DbConnectionInfo.
Thus after MyCouchClient is created, we are no longer able to change the timeout.

If Connection.HttpClient was public we could cast MyCouchClient.Connection from IDbConnection to Connection and get it in order to change timeout but it is protected. Maybe that would not be the correct way to do so but sometime I want to increase or decrease timeout corresponding to what I am downloading/uploading. When processing json I want short timeout but for attachment I want a long timeout. Since it is not recommended to create several HttpClient instance we should be able to modify HttpClient properties.

What do you think about it?

**Comment by danielwertheim** [comment]
HttpClient will not be made public. How ever, you could make a PR where a setter is added for `IConnection`

https://github.com/danielwertheim/mycouch/blob/master/source/projects/MyCouch/IConnection.cs#L12

**Comment by Maxima078** [comment]
If we add a setter , the first initialization within the ctor will be useless, won't it?
What about a new public ctor such as:
`public MyCouchClient(IDbConnection iDbConnection, MyCouchClientBootstrapper bootstrapper = null)`
?

Hence I could inherit from DbConnection, keep a ref to the HttpClient and just set it when creating my singleton instance of Mycouch.
Thank to this I'll be able to manage timeout or event headers (could be usefull for couchdb proxyauth for instance)

Does it seem correct to you? If it is I can quickly make a PR.

**Comment by danielwertheim** [comment]
Are you referring to this? https://github.com/danielwertheim/mycouch/blob/master/source/projects/MyCouch/Net/Connection.cs#L74

Why would it be an issue if you decide to tweak it after it has been constructed by setting a new value as it will be forwarded to the underlying client?

The cTor will not take the connection in. You can make the bootstrapper return whatever connection you want and keep a ref to the HttpClient.

**Comment by Maxima078** [comment]
Sorry for the late. You're right I'll use a custom bootstrapper.

Thank you.
