### ISSUE TITLE
Noting Found saving image and getting image from counchdb

### ISSUE THREAD

**Issue by rishabhack** [danielwertheim/mycouch#156]
Please guide me how can i save image and pdf in counch db.
Noting found for image processing.
Is there is any documentation available for mycouch.

**Comment by danielwertheim** [comment]
As stated in the ReadMe, documentation on My couch can be found in the project Wiki here on GitHub.

You are most likely looking for Attachments: https://github.com/danielwertheim/mycouch/wiki/documentation#attachments 

For CouchDB questions, you could turn to the StackOverflow community and ask your questions there.

**Comment by rishabhack** [comment]
thanks @danielwertheim
