### ISSUE TITLE
Create Custom Views 

### ISSUE THREAD

**Issue by jazeem-azeez** [danielwertheim/mycouch#158]
I it's an nice feature to have,
If we can create custom view at runtime using this library, I couldn't find anything gives and ability for it

A **Put &  Delete API** for Views section 
and this can also load embedded resources to couchdb as views, 
against which one can perform queries **at runtime** .
this facilitates an ability to have **map-reduces scripts in solution** & **enables git versioning** for them.

**Comment by danielwertheim** [comment]
I'm not sure if I think it is something for My couch. Views are maintained as simple documents and can be maintained using the docs API of MyCouch (this is what the tests does). So if you want them embedded you can. While John Doe wants them in JSON files, he can.

If it really should provide value it should allow you to actually express views using C# and lambdas etc. but that is nothing I'm going to build as of now.
