### ISSUE TITLE
Cookie Authentication

### ISSUE THREAD

**Issue by deviousasti** [danielwertheim/mycouch#159]
Basic authentication is okay, but it isn't really recommended.
From the [docs](http://docs.couchdb.org/en/latest/api/server/authn.html#basic-authentication):

> The main drawback is the need to send user credentials with each request which may be insecure and could hurt operation performance (since CouchDB must compute the password hash with every request)

If cookie authentication isn't already supported, I could submit a PR.

What should the API to look like?
One idea is that there could be a sign in method on the `MyCouchClient`.

Thoughts?

**Comment by danielwertheim** [comment]
A "little" late to the game but, no I have no real thoughts on this, but if you (or anyone else) has a suggestion to get things started on this, it would be great.
