### ISSUE TITLE
Examples of using _find mango query.  

### ISSUE THREAD

**Issue by wa1gon** [danielwertheim/mycouch#161]
It would be good to have an example of how to use _find in mycouch.  I saw an example in the issues using select but how do you make the call?

Seems like a great product.  Just started to use it.

thanks
-darryl

**Comment by jlami** [comment]
Did you ever find out how to use it? I saw some code mentioning FindRequest:
https://github.com/danielwertheim/mycouch/blob/8069b9ce0ff3370f329a683b722260192b21be23/source/projects/MyCouch/Requests/FindRequest.cs#L8-L18

https://github.com/danielwertheim/mycouch/blob/8069b9ce0ff3370f329a683b722260192b21be23/source/projects/MyCouch/Contexts/Queries.cs#L73-L83

And a test that uses it:
https://github.com/danielwertheim/mycouch/blob/8069b9ce0ff3370f329a683b722260192b21be23/source/tests/MyCouch.IntegrationTests/CoreTests/QueryTests.cs#L26-L29

**Comment by wa1gon** [comment]
Thanks that was very helpful.

**Comment by adcorduneanu** [comment]
Is there any plan to add bookmark support for the queries functionality (_find endpoint)?
