### ISSUE TITLE
Does this library work with IBM hosted Cloudant?

### ISSUE THREAD

**Issue by cmuentes** [danielwertheim/mycouch#162]
I see this library may have worked with Cloudant in the past, but is anyone actively working on a C# project using this library in C# currently?  The last post i see is from 2014.

**Comment by danielwertheim** [comment]
As I do recall, many Cloudant features were contributed to CouchDB v2 and support for those features were moved from the Cloudant provider to the CouchDB provider. 

I'm not an active Cloudant or CouchDB user anymore and had/have no time to freely be managing a specific version for Cloudant.
