### ISSUE TITLE
query with keys always response null

### ISSUE THREAD

**Issue by mrkeikk** [danielwertheim/mycouch#163]
I use this code:

 using (var client = new MyCouchClient("http://127.0.0.1:5984", "mydb"))
            {
  var query = new QueryViewRequest("users", "login").Configure(q => q
  .Keys(username,password));
 ViewQueryResponse result = await client.Views.QueryAsync(query);

the result always brings me null, but it works on direct URL like:
http://127.0.0.1:5984/sina/_design/users/_view/login?key=["asfasfjkkl@fal.com","22122"]

**Comment by danielwertheim** [comment]
You mix Keys and Key.

Use the Key member that accepts an array.
