### ISSUE TITLE
Help with MyCouchClient Singleton implementation

### ISSUE THREAD

**Issue by iamSathishMohan** [danielwertheim/mycouch#165]
Hi,

I'm using 5.0.3 in my application (i know its very old, but i have plan to upgrade the library soon). As of now, It works really well. Right now i am using one instance of MyCouchClient per task, which creating a socket exceeds limit problem during peak load.

`System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: Only one usage of each socket address (protocol/network address/port) is normally permitted X.X.X.X:5984`

So, i am planning to change my instance logic to single instance per application. Could some one help me with MyCouchClient Singleton implementation code snippet, which i can use for reference. 

Thanks in Advance !

**Comment by danielwertheim** [comment]
There's nothing special with MyCouch when it comes to configuring as a singleton. That is up to your application. E.g. If you use an IoC-framework for dependency resolution, you should be able to configure it there.
