### ISSUE TITLE
FindRequest and SelectorExpression Example

### ISSUE THREAD

**Issue by AyoubGharbi** [danielwertheim/mycouch#166]
Hey! 
I tried to work with FindRequest but I'm always getting "Bad Request" as a response.

Do you know how to fix this?

My code:

`          var request = new FindRequest().Configure(q =>
                q.SelectorExpression("\"is_accessory\": \"true\""));`

**Comment by danielwertheim** [comment]
I just noticed when running against 2.3.1 some integration test fail for Find. E.g. sort. Previously I've had working tests sorting on e.g. `field1` when index contained `field1` and `field2`. Now I seem to need to have an index only for `field1`. Not sure if there are more changes in that area.
