### ISSUE TITLE
[Question] Map Id on Entity to specific property, plus revision and doc type

### ISSUE THREAD

**Issue by kieronlanning** [danielwertheim/mycouch#170]
Is there a way to map the Id field to a specific entity property?

I have some classes I'd like to use that I don't have access to modify, the looks a little like this:

```
public class AggregateType
{
    public AggregateDetails Details { get; set; }

   public int AnIntProperty { get; private set; }

   public string AStringProperty { get; private set; }

   public ComplexType AComplexTypeProperty { get; private set; }

   ...
}

public class AggregateDetails
{
    public string Id { get; set; }
 
    public int Version { get; set; }

    public string AggregateType { get; set; }
   ...
}
```

I'd like to be able to map to the `Details.Id` property for the Id, the `Details.Version` to the the revision property and the doctype to the `Details.AggregateType` property.

Is that possibly using this API?

**Comment by danielwertheim** [comment]
No. It's based on conventions documented in the wiki. You could perhaps
however wrap it and point to the IDs from the root.

**Comment by kieronlanning** [comment]
Thanks @danielwertheim. Presumably that means LINQ queries wouldn’t be as efficient as the index (id, Rev) wouldn’t the ones a consumer would query..?

**Comment by danielwertheim** [comment]
LINQ as in "in-mem" after you have queried or what do you mean? The reason
why I'm confused is that there's no support for translation of LINQ to
Mango or other CouchDB query flavors.

**Comment by kieronlanning** [comment]
Ah, my mistake. I was evaluating this as an API to Couch and thought it had LINQ to CouchDb support...! Sorry!
