### ISSUE TITLE
Updating Documents with attachments

### ISSUE THREAD

**Issue by teamyudin** [danielwertheim/mycouch#18]
Greetings,

I have a question: what is the best practice of updating documents that have attachments?

When I do client.Entities.PutAsync(myEntity), all attachments get wiped out. Do I need to supply a list of all attachments for each update?

Thank You,
Dmitry

**Comment by jonjalberghini** [comment]
In previous version it did not clear the attachments. If I stop using the entities will it go back to the old behavior.

**Comment by jonjalberghini** [comment]
Please help I using the solution above I get missing_stub I can no longer update a document with an attachment. 

Please help,
		public async Task<EntityResponse<CouchDoc>> PatchCouchFileDocument(File newFile, Delta<File> delta )
		{
			EntityResponse<CouchDoc> _CouchDoc = new EntityResponse<CouchDoc>();
			try
			{
				CFile = await GetAsyncEntityCouchDocument(newFile.CouchDocId);
				AssignPatchFileToCouchFile(newFile, delta);
				_CouchDoc = await _db.Entities.PutAsync<CouchDoc>(CFile.CouchDocId,CFile);
				if (!_CouchDoc.IsSuccess || _CouchDoc.IsEmpty)
					throw new Exception("Failed on Couch Update.");
				Debug.Write(_CouchDoc.ToStringDebugVersion());
			}
			catch (Exception Ex)
			{
				Debug.Write(Ex.Message);
			}
			return _CouchDoc;
		}

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Aas.Models
{
	public class CouchDoc

	{
		public string CouchDocId { get; set; }
		public string CouchDocRev { get; set; }
		public string Contributor { get; set; }
		public string EmailAddress { get; set; }
		public string RawEmailDocId { get; set; }

		public string Creator = "Children's Commissioner for Wales";
		public DateTime Date { get; set; }
		//- The datetime the document was added (ISO 8601 (W3C DTF) (Dublin Core).
		public string Description = "Regulatory Support Service - Case Management - Evidence";
		public string CaseDescription { get; set; }

		public string Publisher = "Legal & Investigations";
		
		public string Rights = "This data was created by the Children's Commissioner for Wales";
		
		public string Source = "Aas Application";
		public string Subject { get; set; }
		//Email or File subject (Dublin Core).
		public string Title { get; set; }
		//The name of the file, or subject line of email (Dublin Core).
		public string DocumentType { get; set; }
		//Set to "Raw Email", "Email Attachment", "Email Message", or "File Attachment" "Legacy Document" depending on the source (Dublin Core).
		public bool Processed { get; set; }
		//Set to true and false if email not broken up otherwise always true
		public string Language { get; set; }
		//- A selection of English/Welsh (Dublin Core).
		public int? Relation { get; set; }
		//- The main case Id - from MySQL for this (Dublin Core).
		public Tag[] Tags { get; set; }
		
		public Dictionary<string, CouchAttachment> _attachments;
	}

	public class Tag
	{
		public string Name { get; set; }
	}
	public class CouchAttachment
	{
		[JsonProperty("stub")]
		public bool? Stub { get; set; }

		[JsonProperty("content_type")]
		public string ContentType { get; set; }		

		[JsonProperty("length")]
		public int Length { get; set; }
	}

}

**Comment by jonjalberghini** [comment]
I fixed it. It needs the complete stub. This works for me. Should put this in your documentation.
		public Dictionary<string, CouchAttachment> _attachments;
	}

	public class Tag
	{
		public string Name { get; set; }
	}
	public class CouchAttachment
	{
		[JsonProperty("stub")]
		public bool? Stub { get; set; }

		[JsonProperty("content_type")]
		public string ContentType { get; set; }		

		[JsonProperty("digest")]
		public string Digest { get; set; }

		[JsonProperty("revpos")]
		public int RevPos { get; set; }

		[JsonProperty("length")]
		public Int64 Length { get; set; }
	}

**Comment by danielwertheim** [comment]
The sample code above you mean? Right now there's just a warning about the behavior https://github.com/danielwertheim/mycouch/wiki/documentation#attachments

Or solve it in a nice way.

**Comment by jonjalberghini** [comment]
I still get missing stub on updating a document with entities that has an attachment. The php library works fine same logic. Does you entites library support updating a document that has an attachment.
If not is there one out there you know of? The only reason we choose this was for storage of documents. We are not trying to change the attachment just a field on the document. if I pull the document change nothing and do a put it gives missing stub.
function
		public async Task<EntityResponse<CouchDoc>> PutCouchFileDocument(File newFile)
		{
			EntityResponse<CouchDoc> _CouchDoc = new EntityResponse<CouchDoc>();
			try
			{
				CFile = await GetAsyncEntityCouchDocument(newFile.CouchDocId);
				AssignPutFileToCouchFile(newFile);
				_CouchDoc = await _db.Entities.PutAsync<CouchDoc>(CFile.CouchDocId, CFile.CouchDocRev, CFile);
				if (!_CouchDoc.IsSuccess || _CouchDoc.IsEmpty)
					throw new Exception("Failed on Update.");
				Debug.Write(_CouchDoc.ToStringDebugVersion());
			}
			catch (Exception Ex)
			{
				Debug.Write(Ex.Message);
				throw;
			}
			return _CouchDoc;
		}
Structure 
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Aas.Models
{
	public class CouchDoc

	{
		[Key]
		public string CouchDocId { get; set; }
		public string CouchDocRev { get; set; }
		public string Contributor { get; set; }
		public string EmailAddress { get; set; }
		public string RawEmailDocId { get; set; }

		public string Creator = "Children's Commissioner for Wales";
		public DateTime Date { get; set; }
		//- The datetime the document was added (ISO 8601 (W3C DTF) (Dublin Core).
		public string Description = "Regulatory Support Service - Case Management - Evidence";
		public string CaseDescription { get; set; }

		public string Publisher = "Legal & Investigations";
		
		public string Rights = "This data was created by the Children's Commissioner for Wales";
		
		public string Source = "Aas Application";
		public string Subject { get; set; }
		//Email or File subject (Dublin Core).
		public string Title { get; set; }
		//The name of the file, or subject line of email (Dublin Core).
		public string DocumentType { get; set; }
		//Set to "Raw Email", "Email Attachment", "Email Message", or "File Attachment" "Legacy Document" depending on the source (Dublin Core).
		public string FileName { get; set; }
		public bool Processed { get; set; }
		//Set to true and false if email not broken up otherwise always true
		public string Language { get; set; }
		//- A selection of English/Welsh (Dublin Core).
		public int? Relation { get; set; }
		//- The main case Id - from MySQL for this (Dublin Core).
		public Tag[] Tags { get; set; }
		
		public Dictionary<string, CouchAttachment> _attachments;
	}

	public class Tag
	{

		public string Name { get; set; }
	}

	public class CouchAttachment
	{
		[JsonProperty("stub")]
		public bool? Stub { get; set; }

		[JsonProperty("content_type")]
		public string ContentType { get; set; }		

		[JsonProperty("digest")]
		public string Digest { get; set; }

		[JsonProperty("revpos")]
		public int RevPos { get; set; }

		[JsonProperty("length")]
		public Int64 Length { get; set; }
	}

}

**Comment by danielwertheim** [comment]
I'll take a look. But why don't you then just use the raw JSON using
Documents API and deserialize/serialize as fit?

Or perhaps try and work with any of the Newtonsoft JSON.Net more dynamic
types as the generic type for the Entities API.

**Comment by danielwertheim** [comment]
NOTE! The code below is from my head. Was fiddling a bit on the bus.

Tested reading it out as `client.Entities.GetAsync<JObject>(...)` then used that to update only the `Name` then used something like `client.Documents.PutAsync(id, rev, jobj.ToString())`.

Also seems to work with entities as well. I'll post sample code tonight, but I had something like this:

```
public class Person {
  public string Id { get; set; }
  public string Rev { get; set ;}
  public string Name { get; set; }
  [JsonProperty("_attachments")]
  public Dictionary<string, Attachment> Attachments { get; set; }
}

public class Attachment {
  public bool Stub { get; set; }
  [JsonProperty("content_type")]
  public string ContentType { get; set; }
  public string Digest { get; set; }
  public int RevPos { get; set; }
  public int Length { get; set; }
}

var get = await client.Entities.GetAsync<Person>("myid");
get.Content.Name = "My updated name";

var put = await client.Entities.PutAsync(get.Content);
```

**Comment by jonjalberghini** [comment]
I found the issue and why it is intermittent. I captured traffic on the couch server. 
The put bodies are below but in short it was not spacing. It is the fact that the file name 
is a property and for some reason it is being pascal camel cased. So the attachment name is going from Penguins.jpg to penguins.jpg and couchdb is case sensitive. I traced your packet and save the packet you send if I make the filename correct it works. I am not sure if it is newton or mycouch that is camel casing the properties? is there a attribute I can put on to stop this? I tested very thoroughly and that is the issue. And why It only happened sometimes.
PHP
   "_attachments":{
      "Penguins.jpg":{
         "content_type":"image\/jpeg",
         "revpos":3,
         "digest":"md5-nTd7EM53jEk4s8fixjoimg==",
         "length":777835,
         "stub":true
      }
   }

Mycouch

   "_attachments":{
      "penguins.jpg":{
         "content_type":"image/jpeg",
         "revpos":3,
         "digest":"md5-nTd7EM53jEk4s8fixjoimg==",
         "length":777835,
         "stub":true
      }
   }


myCouch sent this 
{
   "_id":"0536ba0fcdd39efc403da3088a00fb1a",
   "_rev":"3-9f42b6f8906d863504d233b0227d1bc4",
   "$doctype":"couchDoc",
   "creator":"Children's Commissioner for Wales",
   "description":"Regulatory Support Service - Case Management - Evidence",
   "publisher":"Legal & Investigations",
   "rights":"This data was created by the Children's Commissioner for Wales",
   "source":"Aas Application",
   "contributor":"NETDEV\\Jon",
   "rawEmailDocId":"",
   "date":"2015-04-30T08:37:35.4380826-04:00",
   "caseDescription":"This is a test.",
   "subject":"",
   "title":"Testing",
   "documentType":"Case File Attachment",
   "processed":true,
   "relation":6650,
   "language":"English",
   "tags":[
      {
         "name":"Test File"
      }
   ],
   "_attachments":{
      "penguins.jpg":{
         "content_type":"image/jpeg",
         "revpos":3,
         "digest":"md5-nTd7EM53jEk4s8fixjoimg==",
         "length":777835,
         "stub":true
      }
   }
}

PHP sent this

{
   "_id":"0536ba0fcdd39efc403da3088a00fb1a",
   "_rev":"3-9f42b6f8906d863504d233b0227d1bc4",
   "$doctype":"couchDoc",
   "creator":"Children's Commissioner for Wales",
   "description":"Regulatory Support Service - Case Management - Evidence",
   "publisher":"Legal & Investigations",
   "rights":"This data was created by the Children's Commissioner for Wales",
   "source":"Aas Application",
   "contributor":"Crispy-PC-7\\Crispy",
   "rawEmailDocId":"",
   "date":"2015-04-28T12:05:48.1771837+01:00",
   "caseDescription":"This is a test.",
   "subject":"",
   "title":"spaces_554224a5a9203",
   "documentType":"Case File Attachment",
   "processed":true,
   "language":"Welsh",
   "relation":6650,
   "tags":[
      {
         "name":"Email"
      },
      {
         "name":"Test File"
      }
   ],
   "_attachments":{
      "Penguins.jpg":{
         "content_type":"image\/jpeg",
         "revpos":3,
         "digest":"md5-nTd7EM53jEk4s8fixjoimg==",
         "length":777835,
         "stub":true
      }
   }
}

**Comment by danielwertheim** [comment]
In `MyCouchClientBootstrapper` you would need to provide a customized `SerializationContractResolver` https://github.com/danielwertheim/mycouch/blob/master/source/projects/MyCouch.Net45/Serialization/SerializationContractResolver.cs#L12

**Comment by jonjalberghini** [comment]
Thanks for the answer. Is there a sample somewhere? And just a question wouldn't you want to correct this in the package since that property should never be camel cased?

**Comment by crispy-beef** [comment]
We are having the exact same issue with the attachment name property changing case. We were running in PHP using PHP On Couch which worked great, switching to MyCouch has caused a number of issues which need to be resolved. The case for the name property of an attachment should really be left alone. Why change a property which will break an existing install?

**Comment by jonjalberghini** [comment]
I use the _CouchDoc.ToStringDebugVersion(). Is there any way to see body of the post instead of just the url?

**Comment by jonjalberghini** [comment]
For anyone who has this problem 
and add the Jsonproperty to all your field to keep the camel casing.
		[JsonProperty("documentType")]
		public string DocumentType { get; set; }
		
The code below

    public class MySerializationContractResolver : Newtonsoft.Json.Serialization.DefaultContractResolver
    {
        public MySerializationContractResolver() : base(true) { }

        protected override string ResolvePropertyName(string propertyName)
        {
            return base.ResolvePropertyName(propertyName);
        }
    }
	public class CouchHelper
	{

		public CouchHelper()
		{
			MyCouchClientBootstrapper _customAttachmentBS = new MyCouchClientBootstrapper();
            var config = new Lazy<SerializationConfiguration>(() =>
            {
                var contractResolver = new MySerializationContractResolver();
                return new SerializationConfiguration(contractResolver);
            });
			_customAttachmentBS.SerializationConfigurationFn = () => config.Value;
			_db = new MyCouchClient(ConnectionInfo, "ccfwaas", _customAttachmentBS);			
		}

**Comment by danielwertheim** [comment]
@jonjalberghini @crispy-beef if you would use client.Documents nothing with the JSON will be touched. If you use the client.Entities API, there are conventions. You can of course customize the serializer configuration to what ever. BUT, even so, it will have it's conventions, e.g. picking the names of the properties as is defined in the class, "FirstName" --> "FirstName". Now, since not all drivers in the CouchDB echo system is driven by the same organization, there is never a guarantee that another driver would store this as "firstname", "FIRSTNAME", "firstName", "FiRsTNaMe" or even auto aliasing it to reduce storage.... To be safe from this, you really need to just work with the native JSON.

**Comment by crispy-beef** [comment]
@danielwertheim thanks for the information on that. Might be worth putting in the documentation in a little more detail so it doesn't catch others out, thanks for a great library!

**Comment by jonjalberghini** [comment]
I wanted to thank you for the library and it is excellent and thank you for the help.
I understand what you mean now. I am new to couchdb and thought at first the camel casing was couchdb. Everything is working great now. I have one last request  or question is it possible to see the post / put body somewhere in the return object or a debug switch to output it? I would of known right away what was wrong if there was. 
And is there a sample of using the serializer  and client.Documents ?
Thanks again.

**Comment by danielwertheim** [comment]
Currently you can by implementing e.g. a custom `DbConnection` which you configure in the boostrapper, but I'm just releasing something simpler: https://github.com/danielwertheim/mycouch/wiki/documentation#intercept-requests-andor-responses

**Comment by danielwertheim** [comment]
@crispy-beef @jonjalberghini More info about the serialization: https://github.com/danielwertheim/mycouch/wiki/documentation#entities-and-serialization

BTW, it's unfortunate (as I see it) that Couch stores the actual name of the attachment as a key, rather then data to a key: `"filename"`; how-ever, since MyCouch will manage to deserialize, and map keys no matter what casing (so should other serializers in other projects); isn't this a matter of application logic?  You could e.g. store the on disk filename in a meta field, or perhaps always have it `ToLower` or something.

**Comment by jonjalberghini** [comment]
I agree with the filename and thanks so much for putting the hooks to see the complete request.

Thanks again. A great tool!

**Comment by jonjalberghini** [comment]
thanks!! 


----- Original Message -----

**Comment by danielwertheim** [comment]
np

**Comment by riyadh21** [comment]
I need a help. I would like to update document with new attachment which has no attachment before.

This is the sample code.

            DocumentHeaderResponse response;
            using (var client = new MyCouchClient(couchServerAddress, couchDbName))
            {
                var attachemnetRequest = new PutAttachmentRequest(docId, attachmentName, contentType, attachment);
                response = await client.Attachments.PutAsync(attachemnetRequest);
            }

I am trying to add but it is not adding attachment.

Need suggestion and guide how I can achieve it.

Thanks
Riyadh

**Comment by danielwertheim** [comment]
What does the response look like using `response.ToStringDebugVersion()`?

Have you seen this: https://github.com/danielwertheim/mycouch/wiki/documentation#attachments
