### ISSUE TITLE
Calls that do not return content fail in .NET Core 3.1

### ISSUE THREAD

**Issue by alexandru-costan** [danielwertheim/mycouch#185]
I have the following problem.

I have upgraded my application to .NET Core 3.1 and MyCouch to 7.2.0. All requests work as expected except when calling the **GetHeaderAsync** method on a document that does not exist, which fails with a deserialization exception from Newtonsoft.Json.

````System.AggregateException: One or more errors occurred. (No JSON content found. Path '', line 0, position 0.)
 ---> Newtonsoft.Json.JsonSerializationException: No JSON content found. Path '', line 0, position 0.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.PopulateInternal(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.Populate(JsonReader reader, Object target)
   at MyCouch.Serialization.DefaultSerializer.Populate[T](T item, Stream data)
   at MyCouch.Responses.Materializers.FailedResponseMaterializer.GetInfoAsync(HttpResponseMessage httpResponse)
   at MyCouch.Responses.Materializers.FailedResponseMaterializer.SetErrorAndReasonAsync(Response response, HttpResponseMessage httpResponse)
   at MyCouch.Responses.Materializers.FailedResponseMaterializer.MaterializeAsync(Response response, HttpResponseMessage httpResponse)
   at MyCouch.Responses.Materializers.FailedDocumentHeaderResponseMaterializer.MaterializeAsync(DocumentHeaderResponse response, HttpResponseMessage httpResponse)
   at MyCouch.Responses.Factories.ResponseFactoryBase.MaterializeAsync[TResponse](HttpResponseMessage httpResponse, ResponseMaterializer`1 sucessfulResponseMaterializer, ResponseMaterializer`1 failedResponseMaterializer)
   at MyCouch.Responses.Factories.DocumentHeaderResponseFactory.CreateAsync(HttpResponseMessage httpResponse)
   at MyCouch.Contexts.Documents.HeadAsync(HeadDocumentRequest request, CancellationToken cancellationToken)
   at MyCouch.MyCouchStore.GetHeaderAsync(String id, String rev, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
````

The underlying problem comes from the infrastructure changes done in .NET Core 3.0 for HttpResponse.Content stream. The following code from [DefaultSerializer.cs](https://github.com/danielwertheim/mycouch/blob/master/source/projects/MyCouch/Serialization/DefaultSerializer.cs) is the problem
````
private bool StreamIsEmpty(Stream stream)
{
	var stupidExpressionDueToThatLengthThrowsInSomeCases = stream == null || (stream.CanSeek && stream.Length == 0);

	return stupidExpressionDueToThatLengthThrowsInSomeCases;
}
````

In .NET Core 2.2 the stream that is returned in case of a 404 Status Code, is a non-null MemoryStream that has the **CanSeek** and **Length** properties and the method returns the expected result **true** for an empty stream.

However, in .NET Core 3.1 this is not the case. We no longer have a MemoryStream returned but instead, we have a [System.Net.HTTP.EmptyReadStream](https://github.com/dotnet/corefx/blob/release/3.1/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/EmptyReadStream.cs) returned, which lacks the **Length** property and because of that the check fails and returns that the stream is not empty and tries to deserialize the response.

From what I gather there are a couple of possible fixes.
1. Put in a change request on the CoreFX team to include the Length and set it to 0, since this behavior change might affect other projects as well.
1. Change the behavior of the **StreamIsEmpty** method and do extra checks or type checks to handle this new situation.
1. Check in the Populate method from [DefaultSerializer.cs](https://github.com/danielwertheim/mycouch/blob/master/source/projects/MyCouch/Serialization/DefaultSerializer.cs#L133) if the JsonReader is able to read anything
````
using (var jsonReader = Configuration.ApplyConfigToReader(CreateReaderFor<T>(sr)))
{
	if(jsonReader.Read())
	{
		InternalSerializer.Populate(jsonReader, item);
	}
}
````
4. Just add a try/catch block to eat the deserialization error, although this might have unintended side effects.

**Comment by alexandru-costan** [comment]
The issue can be replicated for any call that does not return any kind of content. Just reproduced with the DeleteAsync method.

**Comment by danielwertheim** [comment]
Thanks for reporting and investigating. If you see a simple way to update `StreamIsEmpty` that would be preferred and most welcomed.

**Comment by danielwertheim** [comment]
If I run the following code in .NET Core 3.1

```csharp
using System.IO;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace ConsoleApp1
{
    class Program
    {
        static async Task Main(string[] args)
        {
            using var http = new HttpClient();
            using var req = new HttpRequestMessage(HttpMethod.Head, "https://github.com/a599ab72832f4c418e2eed4bc1392e52");
            var response = await http.SendAsync(req);

            await using var s = await response.Content.ReadAsStreamAsync();
            using var sr = new StreamReader(s, Encoding.UTF8, true);
            using var jr = new JsonTextReader(sr);

            var serializer = new JsonSerializer();

            var x = serializer.Deserialize<Charles>(jr);
        }
    }

    public class Charles
    {
        public int Test { get; set; } 
    }
}
```

I see that I get the new `EmptyResponseStream` and nothing fails and `x` becomes `null`.

How-ever, using the `Populate` path fails. E.g.

```csharp
var x = new Charles();
serializer.Populate(jr, x);
```

According to this, the change should only have to be fixed in the `Populate` path, right?

One could also argue that it perhaps also should be fixed in Newtonsoft. Feels a bit weird that it has different behavior in different paths.

It could also be fixed in the call-stack where this seem to occur e.g. in `FailedResponseMaterializer`. Perhaps it's a valid solution to in there expect the `HttpHeader` to see if content has a length? Don't remember, there was some case where those reported `0` even though there was data. Also noticed there's a dumb setup in there. Trying to deserialize and the overwriting with already existing data, which could be used to not do the deserialization.

Opinions?

**Comment by bitschubse** [comment]
Is there any progress in solving this problem yet? Is there anything we can do to help?
