### ISSUE TITLE
Using multiple couchDB servers

### ISSUE THREAD

**Issue by EugeneKrapivin** [danielwertheim/mycouch#187]
Hey,
I've been reading the documentation and didn't find an option to connect work with multiple servers.
We have multiple couchDB servers (replicated between them selves), I'd like to use all servers in a fallback manner so that if 1 of them crashes it doesn't take my app with it.

Can we achieve such behavior?

Thanks,
Eugene Krapivin.

**Comment by alsitebro** [comment]
@EugeneKrapivin are you thinking of a connection pool type of scenario?
As far as I could get out of the official [CouchDB documentation](https://docs.couchdb.org/en/stable/cluster/index.html), with clustering you would connect to one node address and the interaction/replication between the nodes is abstracted away from the client. 
If you're thinking of a failover type of scenario, you might want to consider using a load balancer or [reverse-proxy](https://docs.couchdb.org/en/stable/best-practices/reverse-proxies.html) sat between you client application and the cluster.
Chapter 4 of [Bradley Holt's Scaling CouchDB](https://www.amazon.co.uk/Scaling-CouchDB-Replication-Clustering-Administration-ebook/dp/B004VB3V2S/ref=sr_1_4?keywords=couchdb&qid=1583704734&sr=8-4) has an example of how you can set up a load balancer for CouchDB using Apache.
I tried this approach in my Docker environment and it worked.

**Comment by EugeneKrapivin** [comment]
@alsitebro Thanks for your response! I've read the documentation as well and find the usage of a reverse proxy to achieve LB and health checks a good enough solution.
However, my current employer seeks to reduce the number of components and prefers that the code preforms the load balancing and fail-over handling.
As it seems to be impossible to do with the library I'll just push to setup an ELB :)

Thanks!
