### ISSUE TITLE
Lucene Search

### ISSUE THREAD

**Issue by iojancode** [danielwertheim/mycouch#193]
Hi, missing a lot Lucene Search. Documented a year ago since version 3.0 https://docs.couchdb.org/en/stable/ddocs/search.html , also included at installation with Chef and Kubernetes.

I saw your commented code, really close, please enable it.

**Comment by iojancode** [comment]
I made a PR for this #193

**Comment by iojancode** [comment]
I made PR #195 to enable this

**Comment by danielwertheim** [comment]
Thanks for the contribution. Release created which should auto publish on NuGet in a short period of time.
