### ISSUE TITLE
Purge support

### ISSUE THREAD

**Issue by iojancode** [danielwertheim/mycouch#207]
Hi, I was implementing a functionality to cleanup my database from thumbstone docs, I found the only way is a complicated procedure in which a new database should be created and everything should be copied to the new one, then drop the previous one. I found /db/_purge documentation at couchdb and I believe is the best way to do it, and implement it at PR #206 so I can use it from my code.

I hope you can merge it and release a new version, thanks

**Comment by danielwertheim** [comment]
v7.7.0-pre1 has been released, which contains this. Thanks for all the work.
