### ISSUE TITLE
_uuids

### ISSUE THREAD

**Issue by danielwertheim** [danielwertheim/mycouch#26]
See docs: http://docs.couchdb.org/en/latest/api/server/common.html#uuids

Should be on `ServerClient`.

**Comment by SrGrieves** [comment]
@danielwertheim This would be great.  Using sequential ids seems important and getting them from couch would be the easiest.

**Comment by danielwertheim** [comment]
If you are only after sequential GUIDs as a strategy for id generation that can be achieved in code, but perhaps the internal storage is better of from getting the values from the same algorithm that is on Couch?
