### ISSUE TITLE
Support for show, list & update

### ISSUE THREAD

**Issue by ThomasWeiss** [danielwertheim/mycouch#42]
It would be nice to have support for the show, list and update features. Proposed prototypes:

**Show**
```
client.Entities.GetAsync<...>("id").WithShow("show-function");
```

**List**
```
var request = new QueryViewRequest("design-doc", "view-function").Configure(q => q.WithList("list-function"));
```

**Update**
```
var request = new UpdateRequest("design-doc", "update-function").Configure(q => q.withId("doc-id").WithBody("body").WithQuery("query"));
client.UpdateAsync(request);
```

Note that I'm still a noob at both CouchDB and MyCouch, so there may be more sensible ways of exposing them!

**Comment by indranilatcal** [comment]
Did we close on where do intend to place Show? Does it have its own context or it goes under Entities as mentioned at the start of this thread?

**Comment by danielwertheim** [comment]
I think it makes sense to have it on GET for Document and Entity as above. As a start.

**Comment by indranilatcal** [comment]
Checked in a changeset for show (#66). If looks right, can apply to others.
Please have a look.

**Comment by indranilatcal** [comment]
Was trying to apply this to Entities but there it cannot deserialze the
response unless it comes out as json.
Shows returning in any other format(html or xml) fails to work with
JsonReader which gets used by default.
Do we see much value with adding this to entities unless shows return jsons?

**Comment by TimSylvester** [comment]
It looks like direct support for update functions never happened.  If you came here looking for it, here's the gist of how I got it to work:

    var docId = UrlParam.Encode(...)
    ...
    var url = $"/_design/{designName}/_update/{funcionName}/{docId}";
    var httpRequest = new HttpRequest(HttpMethod.Put, url);
    using (var httpResponse = await db.Connection.SendAsync(httpRequest).ForAwait()) {
        if (httpResponse.IsSuccessStatusCode) ...
        await httpResponse.Content.ReadAsStringAsync();
        ...
