### ISSUE TITLE
IViews.QueryAsync() does not populate the Id property in the resulting rows

### ISSUE THREAD

**Issue by thedmi** [danielwertheim/mycouch#65]
I'm using `QueryAsync<string>(query)` to get view results and then deserialize the resulting documents myself. 

For cases where I'm only interested in the IDs of the resulting documents, it would be nice to be able to set `query.IncludeDocs` to false, since CouchDB always returns the IDs of the respective documents in view results. This does however not work with MyCouch, because `ViewQueryResponse<TValue, TIncludedDoc>.Row.Id` is always `null`.

**Comment by danielwertheim** [comment]
IncludeDocs has nothing to do with Row.Id. If your index return rows (keys
and optional value) it should have a value for Row.Id. IncludeDocs is false
by default.

**Comment by thedmi** [comment]
Apparently a customized Json.Net IContractResolver mixed up the population of the Id property. Now everything works as expected. Sorry for bothering you!
