### ISSUE TITLE
Added AllOrNothing and NewEdits properties to BulkRequest 

### ISSUE THREAD

**Issue by tohagan** [danielwertheim/mycouch#67]
In my fork I've added support for AllOrNothing and NewEdits properties to BulkRequest 
I needed this badly for a project so would love to see it added. The change is fairly trivial.

I'd send you a PR but my commit screwed up line endings for BulkRequest.cs and MyCouch.Net45.csproj  
I've also not yet added unit tests. 

Here's my commit  that unfortunately touched too many files and lines:
https://github.com/tohagan/mycouch/commit/7acda53fd99c359dff92d67c7931574abf840015

Thanks for MyCouch!

http://wiki.apache.org/couchdb/HTTP_Bulk_Document_API

**Comment by danielwertheim** [comment]
Will add it to the next release. Thanks

**Comment by tohagan** [comment]
Thanks Daniel :)
