### ISSUE TITLE
Sporadic QueryView Error

### ISSUE THREAD

**Issue by mpaul31** [danielwertheim/mycouch#68]
i have a real simple that view that sporadically errors out. the following code works and then if i call it again it would return null for the rows collection. i'm also using cloudant. also, i'm not sure if cloudant only allows so many calls per second to a view (no clue)??

            try {
                var result = Client.Views.QueryAsync<Measurement>(new QueryViewRequest("uom", "all_view")).Result;

                return Ok(result.Rows.Select(r => r.Value));
            }
            catch (Exception e) {
                var log = e.Message;
            }

            return null;

view
function(doc) {
  if (doc.$doctype === "measurement") {
      emit(doc._id, doc);
  }
}

**Comment by mpaul31** [comment]
it seems to do this for all my views if this helps. i wonder if it has to do with the async web api method

**Comment by danielwertheim** [comment]
@willholley any input on this, from a Cloudant perspective?

**Comment by mpaul31** [comment]
@danielwertheim i would also assume if no rows were found the rows collection would have zero elements not null. sounds like an error is occurring

**Comment by danielwertheim** [comment]
If you can reproduce it, what happens if you access the same view using curl or Postman? You could also try and use `QueryRawAsync`, that way we could rule out deserialization etc.

Have you checked `response.IsSuccess` and the `response.StatusCode`? Dump out `response.ToStringDebugVersion()` and you should get status, error, reason etc. if any.

Regarding null, for now you will need to use `response.IsEmpty` or create an extension method.

**Comment by mpaul31** [comment]
hmm the status code is Forbidden.

here is the dump

https://mpaul31.cloudant.com/macrobolic/_design/food/_view/all_view\r\nRequestMethod: GET\r\nStatus: Forbidden(403)\r\nError:forbidden\r\nReason: one of _view, _design, _reader is required for this request\r\nContentType:application/json\r\nETag: \r\n\r\nIsEmpty: True\r\nTotalRows: 0\r\nRowCount: 0\r\nOffset: 0\r\nUpdateSeq:

**Comment by danielwertheim** [comment]
Good. Then it's not an MyCouch issue ;-) 

Configure access to your generated API key in the dashboard at Cloudant and you should be good to go.

**Comment by mpaul31** [comment]
well the problem is i already configured it and it does work for most of the time but sporadically i get the forbidden error even though i pass the credentials.

**Comment by danielwertheim** [comment]
I'll ping tech guys at Cloudant and refer to this. Have you tried intercepting the requests in e.g. Fiddler? Have you tried doing the same request in Curl repeatedly to see if you can reproduce it there?

**Comment by mpaul31** [comment]
ok thanks i'll wait back to hear what they say. i'll try fiddler and curl next.

**Comment by willholley** [comment]
hi @mpaul31 - can you open a Cloudant support ticket so we can continue this outside of GH please? If you can verify the problem with curl that would be very helpful (i.e. rule out MyCouch). Bear in mind that it could be an intermittent problem on the Cloudant side and we don't log the credentials used in a request - our support team should be able to tell you whether there are any known problems on the server you're on though. Any experimental evidence you can provide (e.g. repro in curl and/or with different credentials) would be very helpful.

**Comment by mpaul31** [comment]
@willholley ok i have been able to resolve the issue by creating a new api key. i'll still log the ticket because i am not sure why or how it got corrupted.

thanks for your help

**Comment by Dashue** [comment]
Ah just hit this issue, would perhaps a hint to the possible cause in the error message might be an easy win?

**Comment by danielwertheim** [comment]
Is there something to base it on, as in knowing when to include extra info?

**Comment by Dashue** [comment]
Hmm.. naa actually reading it again it makes sense.
it's a 403 with {"error":"forbidden","reason":"one of _view, _design,
_reader is required for this request"}

I was writing a view at the time so I thought it was an issue related to
the view I was writing.

**Comment by jmarmolejos** [comment]
This seems to be an authentication-related issue. I was getting it while trying to access cloudant without credentials. After building the url with the MyCouchUriBuilder it worked just fine.
