### ISSUE TITLE
Rev collision not notifying client

### ISSUE THREAD

**Issue by mpaul31** [danielwertheim/mycouch#69]
i am testing my concurrency scenarios and it seems when an update occurs and the rev was changed by another user the changes do not take effect (which is good) but there is no exception thrown and IsEmpty still returns false. 

also, i am using cloudant.

Let me know if you need any more details.

**Comment by danielwertheim** [comment]
The `MyCouchClient` does not throw any exception. It is up to you to check properties. https://github.com/danielwertheim/mycouch/wiki/documentation#the-result-is-a-response You could create an extension method for your domain that throws the exception you want.

The `MyCouchStore` (an opinionated abstraction on top of the `MyCouchClient`) throws exception if non successful operation. https://github.com/danielwertheim/mycouch/wiki/documentation#mycouchstore---an-opinionated-abstractionsimplification

**Comment by mpaul31** [comment]
ok so i guess it seems MyCouchCloudantClient uses MyCouchClient under the hood. Can I use MyCouchStore with cloudant?

**Comment by danielwertheim** [comment]
No `MyCouchClient` is not used under the hood in `MyCouchCloudantClient` and it does not extend it either. Reuse is done using composition of "context components" instead (https://github.com/danielwertheim/mycouch/wiki/documentation#contextual-client).

They do how-ever share the same interface `IMyCouchClient` and the `MyCouchStore` can take any implementation of `IMyCouchClient`. But you can also just provide the connection info and then it will create an `MyCouchClient` which works against Cloudant, it just doesn't give you all the features supported by Cloudant. E.g. Lucene searches.

Closing this item for now.

**Comment by mpaul31** [comment]
thank you i'll just create an extension method.
