### ISSUE TITLE
Question - Change Feeds

### ISSUE THREAD

**Issue by mpaul31** [danielwertheim/mycouch#73]
Let's say i have two documents. Meal and Food. Meal contains a collection of Foods. Instead of storing the food id's within the meal i am thinking of storing the food itself. however, when the food gets updated i need the food within the meal to get updated too. is this a case where the change feeds can help out? do you typically run this in a separate thread?

thanks!

**Comment by danielwertheim** [comment]
I guess that would work. Would probably have it running as part of a service.

Do you need to update the data? Or is it ok to live with "outdated" data? E.g. An order with order lines that references articles and stuff. Once an actual order that is fixed and should not take part of any changes to article names etc.
