### ISSUE TITLE
Couldn't find file or assembly

### ISSUE THREAD

**Issue by endikamontejo** [danielwertheim/mycouch#74]
Hi!
I am getting the following error: "Could not load file or assembly 'EnsureThat, Version=2.0.0.39118, Culture=neutral, PublicKeyToken=xxxxxxx' or one of its dependencies. The system cannot find the file specified" when calling to the constructor of MyCouch's MyCouchUriBuilder constructor.

Also I want to comment that in order to sign our project's installer, we sign MyCouch package with the package StrongNaming https://www.nuget.org/packages/Nivot.StrongNaming/

**Comment by danielwertheim** [comment]
What is it that you do? Compiling the source code of MyCouch or...?

**Comment by endikamontejo** [comment]
I just download the MyCouch package through NuGet Package manager, build the solution and sign the unsigned assemblies of the MyCouch project through StrongNaming

**Comment by danielwertheim** [comment]
Well, I have no knowledge of that strong naming NuGet. No project site and no docs for it. Does it work with portable class libs? How does it work with dependent NuGets?

**Comment by endikamontejo** [comment]
I am just having this issue with MyCocuh NuGet, with the rest works fine.
The other possibility I have is to for your repo and try if it work

**Comment by danielwertheim** [comment]
Yeah but do the others have dependencies on other nugets that has multi target DLLs and different dependencies on external NuGets depending on target framework, where also some of them are PCLs?

**Comment by danielwertheim** [comment]
Why not just fork and adapt the build script to sign?

**Comment by endikamontejo** [comment]
I have no idea of which are the dependencies other project have, and for being honest the first time I have seen the concept of PCLs has been today with your project. I will just fork it as for now is the best solution
