### ISSUE TITLE
Missing stub error when updating 

### ISSUE THREAD

**Issue by jonjalberghini** [danielwertheim/mycouch#76]
I get missing stub error when updating couchdb with an attachment that has a filename with spaces.
I can reproduce with futon. Is this a limitation of couchdb?
It lets me put the filename in with spaces but I can never edit it.

Thanks

**Comment by danielwertheim** [comment]
For general discussions and issues around CouchDB, I would use either StackOverflow of the proper mailing list as defined here: http://couchdb.apache.org/

From the standpoint of MyCouch, there might be something I can do if you provide more info to reproduce the issue. Could it be something like wrong URL encoding?
