### ISSUE TITLE
Support new_edits on PUT

### ISSUE THREAD

**Issue by dittodhole** [danielwertheim/mycouch#77]
According to https://wiki.apache.org/couchdb/HTTP_Document_API there is a `new_edits` queryString-paramter to enable naive overrides.
It would be helpful if there was a matching variant in MyCouch (with `MyCouchClient.Documents` as well as with `MyCouchStore`).

**Comment by dittodhole** [comment]
Just realised that you are already appending `new_entries` when there is no `rev` supplied. The problem is, that this only works for gen0 instances, beyond that a `rev` is mandatory (even if you supply `new_entries`).

**Comment by danielwertheim** [comment]
Out of internet access in Greek islands. Will attend your issues (unless
you can manage in the source) when back next week.

**Comment by danielwertheim** [comment]
I'm not doing anything with `new_entries`. Look at difference in XML comments between StoreAsync and SetAsync https://github.com/danielwertheim/mycouch/blob/master/source/projects/MyCouch.Net45/IMyCouchStore.cs#L80
