### ISSUE TITLE
Error with MyCouchClient (storing Document)

### ISSUE THREAD

**Issue by dittodhole** [danielwertheim/mycouch#78]
Version A:
```csharp
using (var myCouchClient = new MyCouchClient("http://localhost:5984",
											 "database"))
{
	EnsureTypeView<Foo>(myCouchClient,
						"foos");
}
```

Version B:
```csharp
using (var myCouchClient = new MyCouchClient("http://localhost:5984/database"))
{
	EnsureTypeView<Foo>(myCouchClient,
						"foos");
}
```

Where `EnsureTypeView` is implemented as follows:
```csharp
private void EnsureTypeView<T>(MyCouchClient myCouchClient,
							   string viewName)
{
	var mapReduceFunction = @"
function (doc) {
	if (doc.%DOCTYPE% == '%ENTITY%') {
		emit(doc.%ID%, doc);
	}
}";
	mapReduceFunction = mapReduceFunction.Replace("%DOCTYPE%",
												  DocTypePropertyName)
										 .Replace("%ENTITY%",
												  typeof (T).Name.ToCamelCase())
										 .Replace("%ID%",
												  JsonScheme._Id);

	var obj = new JObject
			  {
				  {
					  "_id", "_design/database"
				  },
				  {
					  "language", "javascript"
				  },
				  {
					  "views", new JObject
							   {
								   {
									   viewName, new JObject
												 {
													 {
														 "map", mapReduceFunction
													 }
												 }
								   }
							   }
				  }
			  };
	var jsonString = JsonConvert.SerializeObject(obj);

	myCouchClient.Documents.PostAsync(jsonString)
				 .Wait();
}
```
DISCLAIMER: I know, this only supports one view - this is just for demo

With Version A I do get following exception:
> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive. ---> System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine. ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine
>    at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
>    --- End of inner exception stack trace ---
>    at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
>    at System.Net.HttpWebRequest.MakeMemoryStream(Stream stream)
>    --- End of inner exception stack trace ---
>    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
>    at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
>    --- End of inner exception stack trace ---
>    at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
>    at Microsoft.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at Microsoft.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at MyCouch.Contexts.Documents.<PostAsync>d__19.MoveNext()

**Comment by dittodhole** [comment]
Sorry, my mistake ...
It should be `new MyCouchClient("http://localhost:5984/database", "database")` ... But isn't this a bit ... noisy?!

**Comment by danielwertheim** [comment]
You don't have to specify DB-name, that is optional and defaults to null. This is if you are behind a proxy etc.
