### ISSUE TITLE
Expose a constant for the DocType property name

### ISSUE THREAD

**Issue by dittodhole** [danielwertheim/mycouch#80]
In the ctor of `MyCouch.Serialization.Conventions.SerializationConventions` is the initialization of all the meta conventions, which get applied on serialization. As I am planning to implement a Lucene contrib to MyCouch it would be tremendously helpful if you would expose the `"$doctype"` somewhere for further usage.

**Comment by danielwertheim** [comment]
What is it that it will be used for?

Sounds interesting, what do you mean by a Lucene contrib in the context of MyCouch?

**Comment by dittodhole** [comment]
Actually I've already started the development: https://github.com/dittodhole/MyCouch.Fulltext

Basically you register properties with `client.Fulltext.AddForIndexing` and when you are finished you start listening on changes with `client.Fulltext.ConnectToChanges` (which opens a continuous feed on changes from seq 0 - I know, not very performant atm). This then enables you to do a fulltext search on the data with `client.Fulltext.Search` instead of building a view with sliced keys and do an artifical ordering.

**Comment by dittodhole** [comment]
The thing is, that I've tried to access it via `SerializationConfiguration.Conventions.DocType` but the `PropertyName`-property is protected ...

**Comment by danielwertheim** [comment]
Yes, I looked at that. I'm thinking of exposing a read only MemberName.
