### ISSUE TITLE
null in complex key of view

### ISSUE THREAD

**Issue by sgeef** [danielwertheim/mycouch#83]
Hi daniel, 

I got a view which returns some id's and a date. Now since some time, we made one of the id's optional and the view picks this up in a correct way for us. it returns an complex key like: [null, "f41c9f60-d0da-4394-a273-704e928b1311", 1434701201]

but when i put null in my object array and pass it on to the StartKey, the url generated will contain nothing. 
According to how Cloudant/couchdb picks this up for null values, i guess that this is a bug. 

Also i couldn't think of any work around to make it possible to query such complex key..

Looking forward to your response!

**Comment by danielwertheim** [comment]
Don't know how that should be passed to Couch or Cloudant. But if you find out how, by curl or something, I'll fix the URL generation.
