### ISSUE TITLE
MyCouchClient constructor 

### ISSUE THREAD

**Issue by logtheta** [danielwertheim/mycouch#84]
Hello,
it seems that using

var client = new MyCouchClient("http://localhost:5984/mydb")

is different than using

var client = new MyCouchClient("http://localhost:5984/","mydb")

If I use the first to call a view it works while the second one not!

Looking at the variable it seems an error in the request:

In the first case will be : http://localhost:5984/mybd/_design...
in the second one will be http://localhost:5984/_design  (no db)

Thanks,
Giuseppe

**Comment by danielwertheim** [comment]
Will be written for next major bump release, where you will need to define server-endpoint and dbname explicitly.
