### ISSUE TITLE
MyCouchStore.GetHeadersAsync throws NPE on missing values

### ISSUE THREAD

**Issue by ncruces** [danielwertheim/mycouch#85]
Both overloads of `MyCouchStore.GetHeadersAsync` throw a `NullReferenceException` for documents missing from the database.

My suggestion would be either skipping these documents, or outputing a `DocumentHeader` with a nulled `Rev`.

**Comment by ncruces** [comment]
I came across this while trying to get a list of current revisions for documents I want to bulk create/update.

My workaround is this (which means it can be done):
```
var rows = await store.QueryAsync<AllDocsValue>(new Query("_all_docs").Configure(r => r.Keys(keys)));
var revs = rows.Where(r => r.Id != null).ToDictionary(r => r.Id, r => r.Value.Rev);
```

**Comment by danielwertheim** [comment]
The idea is that it should return null if the document is not found

https://github.com/danielwertheim/mycouch/blob/master/source/projects/MyCouch.Net45/MyCouchStore.cs#L309

Any more input on what line that throws?

**Comment by ncruces** [comment]
Hi, it's `GetHeadersAsync` that throws, Header**s**.

The stack trace is:
```
   at MyCouch.MyCouchStore.<GetHeadersAsync>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

I don't have a line, I'm using the Nuget package, and I have no PDBs, but I'm assuming it's [here](https://github.com/danielwertheim/mycouch/blob/master/source/projects/MyCouch.Net45/MyCouchStore.cs#L330) and [here](https://github.com/danielwertheim/mycouch/blob/master/source/projects/MyCouch.Net45/MyCouchStore.cs#L346).

In both cases `row.Id` and `row.Value` should both be null, and accessing `row.Value.Rev` throws.

I'd do either one of:
```
new DocumentHeader(row.Id, row.Value == null ? null : row.Value.Rev)
```
Which returns `(null, null)` for inexistent docs, or:
```
new DocumentHeader(row.Key, row.Value == null ? null : row.Value.Rev)
```
Which returns `(_id, null)` instead (`key == _id`).

**Comment by ncruces** [comment]
I have a pull request (#88) that I can confirm fixes the NPE for me.

**Comment by ncruces** [comment]
A bigger change I'd also need is: for deleted documents, `_all_docs` returns:
```json
{"id":"$ID","key":"$ID","value":{"rev":"$REV","deleted":true}}
```

I'd need to add a `Deleted` to `AllDocsValue` [here](https://github.com/danielwertheim/mycouch/blob/master/source/projects/MyCouch.Net45/MyCouchStore.cs#L620), but I'd also need add it to `DocumentHeader`, which is used pretty much everywhere.

My use case is: I have a list of documents I want to update through `_bulk_docs`. I need to first fetch the list of current revs for those documents through `_all_docs`. Some documents might never have existed in the DB - MyCouch crashes (#85). Some might have been deleted - MyCouch returns the rev of deletion, using that rev for `_bulk_docs` generates a conflict.

Right now I'm querying `_all_docs` myself, as a workaround.
Would you fancy a pull request fixing this?

**Comment by danielwertheim** [comment]
When a specified key against `_all_docs` does not give a match, it does not include an `id` for that row, but only the searched `key`, and an `error`. Will ignore these rows by looking at `Id == null`

E.g. `GET http://development:5984/test/_all_docs?keys=["1", "3"]` where `3` is missing

```
{
  "total_rows": 2,
  "offset": 0,
  "rows": [
    {
      "id": "1",
      "key": "1",
      "value": {
        "rev": "1-967a00dff5e02add41819138abb3284d"
      }
    },
    {
      "key": "3",
      "error": "not_found"
    }
  ]
}
```

**Comment by danielwertheim** [comment]
Released with `v4.0.0-rc3`

**Comment by ncruces** [comment]
OK, skipping those lines is fine as well, and fixes the crash.

What about deleted documents? That information is lost as well.

Note: this is fine by me, I'll continue custom querying `_all_docs`, if needed be.

**Comment by danielwertheim** [comment]
Reopen for adding support for Gets of deleted...

**Comment by danielwertheim** [comment]
@ncruces Hope the last commit helps. Released in `v4.0.0-rc4`

**Comment by ncruces** [comment]
Seems perfect, thanks!

This is now positively nitpicking, but any reason `AllDocsValue` is private? I have a similar class on my side, to query `SystemViewIdentity.AllDocs`.

**Comment by danielwertheim** [comment]
Since it came out as a need when building the opinionated MyCouchStore and I didn't want the world to start taking dependencies on it (using it) just because it's "there"... But if there's an usage for it, then open an issue for an enhancement that it should be made public...and why.
