### ISSUE TITLE
support for CoreCLR

### ISSUE THREAD

**Issue by opiethehokie** [danielwertheim/mycouch#87]
Are there plans to make mycouch usable when only the CoreCLR is installed?

**Comment by JanSichula** [comment]
I second the the question and will patiently await the answer.

**Comment by danielwertheim** [comment]
Yes, but no ETA. But feel free to clone and get it working and give
feedback on what's needed.

**Comment by matsprea** [comment]
I'm tryng to get it working on CoreClr, you can find my fork here https://github.com/matsprea/Couch.Core

**Comment by danielwertheim** [comment]
Ensure that is soon being published. Follow progress here: https://github.com/danielwertheim/Ensure.That/issues/16

MyCouch will be next, I will drop the .Net4.0 PCL project and instead only have projects for 4.5, 4.6 and CoreCLR.

**Comment by danielwertheim** [comment]
Work has begun. Progress can be followed in this branch: https://github.com/danielwertheim/mycouch/tree/feature/vnext

**Comment by danielwertheim** [comment]
Solved with PCL supporting aspnetcore and universal app. Included in develop. Going out next release.
