### ISSUE TITLE
ArgumentException while attempting put document to database

### ISSUE THREAD

**Issue by bane2** [danielwertheim/mycouch#89]
I get an ArgumentException, when i run the following program. I read and used your README file /documentation but i can't put the entity to the database. Putting a document also don`t work.

notes:
   - no port is specified because port forwarding from port 80 to 5984 in my router is configured
   - no user and password is specified, because they arn`t required for the database (only testcase)
   - tested putting document via curl -> successfull
 

![issue1](https://cloud.githubusercontent.com/assets/11395233/10074439/356291a8-62d0-11e5-93f9-f4a0ff8f2da6.PNG)

![issue2](https://cloud.githubusercontent.com/assets/11395233/10100786/554b5aa8-6394-11e5-96c4-100d3442ecca.PNG)

![issue3](https://cloud.githubusercontent.com/assets/11395233/10100792/5a95511c-6394-11e5-9676-d57d70172f32.PNG)

**Comment by danielwertheim** [comment]
I'm sorry but what you are showing makes no sense. What is `doSomethingAsync`?

Also, what is `MyClient`? That is not part of MyCouch.

**Comment by bane2** [comment]
Hey sorry there are missing 2 pics. I saw them in my post?! I will add them when i am at my desktop.

**Comment by danielwertheim** [comment]
Does it say what argument? Are you using the NuGet package or the code in the develop branch?

If NuGet code. Try and include the dbname in the URL instead.

**Comment by bane2** [comment]
Hi, i use Nuget package (Nuget updated before installing mycouch). Also, i tested including dbname in URL yet. I doesnt fixed the problem.

Visual Studio dont say what Argument and i cant debug it. So the exception must be raised in mycouch-code.

**Comment by danielwertheim** [comment]
https://github.com/danielwertheim/mycouch/wiki/documentation#entities

Your model needs two properties. Different conventions are supported. Read at link above.

**Comment by bane2** [comment]
Ok thanks, your suggested changings solved the problem with the ArgumentException and the program quits with ok, but no document is inserted in the database "test1".

I tested many variations of URL and dbName constellations but it doesn't helped.
I also tested Put as well as Post requests to insert document.
Perhaps you can use my Url and dbName to test, if you can put any document/data to the database?!

Thanks..Marco

**Comment by danielwertheim** [comment]
Do you use the default port of `5984`? Can you `POST` using e.g. cUrl or Postman?

**Comment by danielwertheim** [comment]
You have a simple sample here (https://github.com/danielwertheim/mycouch/blob/master/source/samples/MrLab/Program.cs) that will create the database (maybe that is not OK, then just skip the `client.Database.PutAsync()` call.

Note that I use basic auth in the sample passing user `sa` password `test`.

**Comment by danielwertheim** [comment]
You have three documents in it: http://www.mkretzschmann.de/test1/_all_docs

**Comment by bane2** [comment]
Yes but these documents were inserted by futon.

**Comment by danielwertheim** [comment]
http://www.mkretzschmann.de/test1/mycouchtest1

Created using sample code
