### ISSUE TITLE
Ints dislike QueryViewParametersConfigurator.Keys<T>()

### ISSUE THREAD

**Issue by jasonholloway** [danielwertheim/mycouch#93]
I'm a bit hamstrung in my investigations because shared projects don't agree with Windows 7, but it seems that there might well be a bug in the above function.

Passing in an array of value-type keys only manages to set the IQueryParameters.Keys property to null, as such an array can't be coaxed to an object array using the 'as' operator. You have to explicitly box, via Linq or something.

Your test doesn't cover this possibility, so I'm taking it it isn't intentional.

Otherwise, thanks for the library!

**Comment by jasonholloway** [comment]
And (it's late so maybe I'm doing something stupid) but I could swear that no returned rows get materialized when I go down the QueryViewRequest route, none at all...

I can see them on Fiddler, and the ViewQueryResponses say successful, but the rows array is always empty. Getting the feeling I should go to bed...

**Comment by danielwertheim** [comment]
You are right. There's an issue there. For now, instead of

```csharp
var req = new QueryViewRequest("persons", "score").Configure(q => q.Keys(10, 30));
```

use

```csharp
var req = new QueryViewRequest("persons", "score")
 {
    Keys = new object[] {10, 30}
 };
```

**Comment by danielwertheim** [comment]
Bug fix available in https://www.nuget.org/packages/MyCouch/4.0.0-rc5

**Comment by jasonholloway** [comment]
Thanks!
