### ISSUE TITLE
Deserialization exceptions

### ISSUE THREAD

**Issue by jasonholloway** [danielwertheim/mycouch#94]
Hello again,

I was having some problems last night getting view results to materialize into a row array within ViewQueryResponse - I was just getting a value of null, with the IsEmpty flag set, despite the database definitely returning the expected http payload.

It turns out, kind of inevitably, that the problem was mine, in that I'd not given my entity class a correctly-typed ID property (should have been string, but was int), which was obviously causing something in the deserialization to fail.

This is all fair enough, but could I lodge a request for some kind of exception to be raised in these cases? Daft users should be confronted with their own errors. The returned null just made me suspect other parts of the stack.

**Comment by danielwertheim** [comment]
Can you show my some code. As in:

ModelIn
ModelOut
And JSON response from view

**Comment by jasonholloway** [comment]
This seems to shows the same problem, only without the complication of views:

```c#
class GoodModel
{
    public string Id { get; set; }
    public string Hello { get; set; } = "Blah blah blah";
}


class BadModel
{
    public string Id { get; set; }
    public int Hello { get; set; }
}


void Test() {
    using(var couch = new MyCouchClient(@"http://localhost.:5984/bbapp", "bbapp")) {
        if(couch.Documents.GetAsync("model/1").Result.IsEmpty) {
            couch.Entities.PostAsync(
                            new GoodModel() { Id = "model/1" })
                            .Wait();
        }

        var resp = couch.Entities.GetAsync<BadModel>("model/1").Result;

        //above shows empty, when data was returned, and only deserialisation failed

        Debug.Assert(!resp.IsEmpty);
    }
}
```

**Comment by jasonholloway** [comment]
And the json returned is fine:
```json
{"_id":"model/1","_rev":"1-e86e35190b217cc3b6d21a1938dcac15","$doctype":"goodModel","hello":"Blah blah blah"}
```

**Comment by danielwertheim** [comment]
Actually there's an bug that causes this. The exception should bubble, but due to stupid `async void` by me (yes I know it should only be used for eventhandlers) the exception is not returned and ....

Fixing all those places now. Will be out in next release.

**Comment by jasonholloway** [comment]
A-ha, that's interesting to know actually. One to look out for in future!

**Comment by danielwertheim** [comment]
@jasonholloway Now fixes gives

![image](https://cloud.githubusercontent.com/assets/196044/11170953/4aa3aa20-8be3-11e5-9ca1-8bd86cf64ac3.png)

**Comment by danielwertheim** [comment]
Released in `v4.0.0-rc6`

**Note** In `v4.0.0` when constructing a client, you pass the server url as one argument and the dbname as another argument.

**Comment by jasonholloway** [comment]
Cheers, thanks again!

**Comment by jasonholloway** [comment]
And you're right about the dbname of course! Another artefact of late-night hacking.
