### ISSUE TITLE
Change heartbeats pushed through ObserveContinuous

### ISSUE THREAD

**Issue by jasonholloway** [danielwertheim/mycouch#95]
Hello again (and apologies!)

Got another bug: when listening for changes with the ObserveContinuous observable, each heartbeat is coming through as an event.

This is my set-up if it makes a difference:

``` csharp
var changes = couch.Changes.ObserveContinuous(
                                new GetChangesRequest() {
                                    Heartbeat = 1000,
                                    Feed = ChangesFeed.Continuous,
                                    Since = lastSeq.ToString(),
                                    IncludeDocs = true
                                },
                                _cancelSource.Token);
```

**Comment by danielwertheim** [comment]
What do you mean? If you use heartbeats you get heartbeats?

**Comment by danielwertheim** [comment]
@jasonholloway can you elaborate? Are you saying you want MyCouch to filter out heartbeats? Why? How would you as a consumer then know that it is alive?

**Comment by jasonholloway** [comment]
Well, I expected the connection management to be nicely encapsulated as elsewhere. I can see though how this wouldn't actually be perfect: you couldn't just have the client repeatedly sending requests if there was something properly wrong with the connection - I'm with you on that one. I apologise for immediately screaming 'bug'.

But - the only way a heartbeat event could be of any use would be if the user timed the interval between each one, and deduced that the connection had been lost from a timeout. What's really needed is a single, positive event to be sent, signifying that the flow of changes has halted. It so happens that this is baked into Rx, in the OnCompleted event (or, indeed, the OnError one). I think MyCouch should swallow the heartbeats, and send one of these when the underlying http request returns (maybe it already does).

So you could consume it as so:
```csharp
changes.Do(s => { /* change processing */ })
        .Finally(() => { /* re-establish connection, possibly */ });            
```

**Comment by danielwertheim** [comment]
I'm going to close this, because as of now MyCouch is not trying to be intelligent in these parts but just allow you to get a stream of changes. So if you say you want heartbeats, when it's just a heartbeat, and therefore not representing a change, you will need to treat that as a consumer.

Yes, it does call Complete when it stops listening to the stream, but as it is continuous, it will only happen when cancelled. It does miss `OnError`. Opening an item for that: #118
