### ISSUE TITLE
$doctype is added even though it's already there.

### ISSUE THREAD

**Issue by PetePeter** [danielwertheim/mycouch#96]
Gday.

When doing: 
blah.Entities.Serializer.Serialize(item) I can end up with two $doctype present in the serialised string if 'item' happens to have a property such as:

```
    [JsonExtensionData(ReadData = true, WriteData = true)]
    public Dictionary<string, object> ExtensionData { get; set; } = new Dictionary<string, object>();
```

The steps to cause the problem
1. I make item and write to the database (at write time, there is no $doctype in ExtensionData)
2. I read the item from the database (at read-time, $doctype is set in ExtensionData)
3. I make a modification and write the item to the database. Then I get an error. Because ExtensionData already has $doctype and then it seems that Entities.Serializer adds $doctype without checking again.

My current work around is to remove $doctype after I read every item off the database.

Version: 4.0.0 on .net 4.6

**Comment by danielwertheim** [comment]
Yes, the doctype (when using Entities.Serializer not Documents. Serializer)
will be appended to the JSON on its way in. It's not intended to be used
other than in CouchDB itself. E.g. when writing views. So should not need
to pull it out.

Will see if I can fix that in an efficient manner.

**Comment by Oscaroo-au** [comment]
Gday.
Yep. I don't use the Entities.Serializer on its own. I was having problem with the Entities.Put with an error and I used the Entities.Serializer to see what was being serialized and saw the duplication then. Removing the duplicate from the ExtensionData seemed to fix it.

**Comment by danielwertheim** [comment]
Did you use Json.Net serialization callbacks for that or...?

**Comment by Oscaroo-au** [comment]
I remove a copy of the $doctype from the ExtensionData immediatelly after deserialising my object. I do this by .Remove the key "$doctype" from the dictionary (in my object) that is marked with the ExtensionData attribute. Thus, when that object goes to be serialised again, MyCouch will prepend a new $doctype and all will be well again.
