### ISSUE TITLE
Dropped support for .NET 4.0

### ISSUE THREAD

**Issue by dittodhole** [danielwertheim/mycouch#97]
Is there any particular reason for dropping support of .NET 4.0?

**Comment by danielwertheim** [comment]
Yes...

One is: http://danielwertheim.se/2014/10/11/uri-behaves-differently-in-net4-0-vs-net4-5/

One is: "Do not use Microsoft.Bcl.Async to enable async on ASP.Net" https://books.google.se/books?id=nsaUAwAAQBAJ&pg=PA16&lpg=PA16&dq=c%23+async+do+not+use+the+bcl+async+asp.net&source=bl&ots=tNJRHZECvL&sig=QgG9owZfUseoFDT_YDGIYVM1qaM&hl=en&sa=X&ved=0ahUKEwipisOTqL7JAhWkjnIKHYVvASkQ6AEIODAE#v=onepage&q=c%23%20async%20do%20not%20use%20the%20bcl%20async%20asp.net&f=false

One is: I don't want to maintain to many "versions" of the same code base.

**Comment by dittodhole** [comment]
:+1: thanks for your elaboration!

**Comment by danielwertheim** [comment]
Maybe I can come to better thoughts, but not today. Anything acute?

**Comment by dittodhole** [comment]
Actually no, just wanted to not depend on legacy versions ;)

**Comment by danielwertheim** [comment]
Found another one http://blogs.msdn.com/b/dotnet/archive/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1.aspx

**Comment by dittodhole** [comment]
:+1: thanks for that information. unfortunately, I am in the situtation where I cannot force an upgrade to a newer .NET framework version, as some of our customers are stuck on Windows XP (... no - don't argue that ... I already did :frowning:)
