### ISSUE TITLE
Multi key views

### ISSUE THREAD

**Issue by acken** [danielwertheim/mycouch#98]
I am using views with multiple keys. like emit([doc.name,doc.date], doc);. When I want to query this by the first key I would have to do query.Configure(fun q -> q.StartKey("[\""+user+"\"]").EndKey("[\""+user+"\",{}]")... which I hoped would give me a query like http://localhost:5984/mydb/_design/articles/_view/documentsByPersonAndDate?startkey=["John"]&endkey=["John",{}], However what is generated is /mydb/_design/articles/_view/documentsByPersonAndDate?descending=true&reduce=false&startkey=%22%5B%22John%22%5D%22&endkey=%22%5B%22John%22%2C%7B%7D%5D%22&limit=5. Which would be /mydb/_design/articles/_view/documentsByPersonAndDate?descending=true&reduce=false&startkey="["John"]"&endkey="["John",{}]"&limit=5. The whole key expression is wrapped in quotes which breaks the query.

Am I doing this wrong or is there a bug here?

-Svein Arne

**Comment by danielwertheim** [comment]
What if you pass in an native .net array instead, containing an element with the value of `user`?

**Comment by danielwertheim** [comment]
@acken did that work?

**Comment by danielwertheim** [comment]
Closing as no feedback is provided by reporter with checking using native .net array instead.

**Comment by reddyBell** [comment]
I'm wondering, how do you achieve : StartKey : ["a", {}] with MyCouch ? I specifically mean the {} empty term. (This is part of the OP question so I just plug it here :)  )

**Comment by danielwertheim** [comment]
Pass an array with one element being "a" and the other an empty object: `new object[] {"a", new {}}`

**Comment by reddyBell** [comment]
It did it, thanks a lot !
